import { readFileSync } from "node:fs";
import { expect, test, type Page } from "@playwright/test";

const greenIds = new Set(JSON.parse(readFileSync(new URL("../research/association-collection.json", import.meta.url), "utf8")).filter((r: any) => r.associations.niveau === "verte").map((r: any) => `catalog-${r.id}`));

async function fresh(page: Page) {
  await page.goto("/");
  await expect(page.getByTestId("onboarding-view").or(page.getByTestId("home-view"))).toBeVisible();
  if (await page.getByTestId("onboarding-view").isVisible()) await page.getByTestId("onboarding-skip").click();
  await expect(page.getByTestId("home-view")).toBeVisible();
}
async function library(page: Page) {
  await page.getByRole("button", { name: "Recette", exact: true }).click();
  await page.getByRole("tab", { name: "Catalogue", exact: true }).click();
  await expect(page.getByLabel("Filtrer les associations")).toBeVisible();
}

test("collection, orange pairs, scaled portions and complete meal", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  await fresh(page); await library(page);
  const filter = page.getByLabel("Filtrer les associations");
  await filter.selectOption("collection");
  await expect(page.locator(".catalogue-count")).toHaveText("457 résultats");
  await filter.selectOption("verte");
  await expect(page.locator(".catalogue-count")).toHaveText("300 résultats");
  await filter.selectOption("orange");
  await expect(page.locator(".catalogue-count")).toHaveText("157 résultats");
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Riz complet aux dés de fenouil");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await expect(page.getByTestId("association-notice")).toContainText("Associations orange");
  await expect(page.getByTestId("association-notice").locator("li").first()).toContainText("+");
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await expect(page.locator(".catalogue-detail .ingredient-list")).toContainText("280 g");
  await expect(page.locator(".catalogue-detail .steps")).toContainText("700 ml");
  await page.screenshot({ path: info.outputPath("recette-orange.png"), fullPage: true });
  await page.getByRole("button", { name: "Retour", exact: true }).click();
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Cabillaud en papillote de chou et fenouil");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await page.getByTestId("flow-current").getByTestId("compose-meal").click();
  const builder = page.getByTestId("flow-current");
  await expect(builder.getByTestId("meal-builder-view")).toBeVisible();
  await expect(builder.getByTestId("meal-builder-anchor")).toContainText("Cabillaud en papillote de chou et fenouil");
  await builder.getByRole("tab", { name: "Entrée", exact: true }).click();
  await expect(builder.getByTestId("meal-builder-candidate-r875")).toBeVisible();
  await builder.getByRole("tab", { name: "Dessert", exact: true }).click();
  await builder.getByTestId("meal-builder-candidate-r824").click();
  await expect(builder.getByRole("tab", { name: "Entrée", exact: true })).toHaveAttribute("aria-selected", "true");
  await expect(builder.getByTestId("meal-builder-candidate-r875")).toHaveCount(0);
  await builder.getByTestId("meal-builder-candidate-r1017").click();
  const summary = page.getByRole("dialog", { name: "Votre repas", exact: true });
  await expect(summary.getByTestId("meal-builder-status")).toContainText("Associations orange présentes");
  await expect(summary.getByTestId("meal-builder-status")).toContainText("orange");
  await expect(summary.getByTestId("meal-builder-slot-dessert")).toContainText("Crème glacée minute d'avocat et banane");
  await page.screenshot({ path: info.outputPath("constructeur-repas-complet.png"), fullPage: true });
  await summary.getByRole("button", { name: "Fermer « Votre repas »" }).click();
  await page.getByRole("button", { name: "Retour", exact: true }).click();
  await page.getByRole("button", { name: "Retour", exact: true }).click();
  await filter.selectOption("verte");
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Papillotes : poulet, brocoli, poivron");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await expect(page.locator(".catalogue-detail .association-notice")).toContainText("Associations vertes");
  await expect(page.locator(".catalogue-detail .association-notice li")).toHaveCount(0);
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await expect(page.locator(".catalogue-detail .ingredient-list")).toContainText("760 g");
  await page.locator(".catalogue-detail .association-notice").scrollIntoViewIfNeeded();
  await page.screenshot({ path: info.outputPath("nouvelle-recette-verte.png"), fullPage: true });
  const sizes = await page.locator("body").evaluate(el => [el.clientWidth, el.scrollWidth]);
  expect(sizes[1]).toBeLessThanOrEqual(sizes[0] + 1);
  expect(errors).toEqual([]);
});

test("saved association profile governs generation and shopping", async ({ page }) => {
  await fresh(page);
  await page.getByRole("button", { name: "Ajuster mon profil" }).click();
  await page.getByLabel("Règles d’association du générateur").selectOption("green");
  await page.getByLabel("Temps actif maximum en cuisine (min)", { exact: true }).fill("45");
  await page.getByRole("button", { name: "Enregistrer mon profil" }).click();
  await page.reload();
  await expect(page.getByTestId("home-view")).toBeVisible();
  await page.getByRole("button", { name: "Générer ma semaine" }).click();
  await page.getByRole("button", { name: "Créer ma semaine" }).click();
  await page.getByRole("button", { name: "Voir ma semaine" }).click();
  await expect(page.getByTestId("week-view")).toBeVisible();
  const stored = await page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!));
  expect(stored.profile.associationMode).toBe("green");
  expect(stored.currentPlan.meals).toHaveLength(14);
  for (const meal of stored.currentPlan.meals) expect(greenIds.has(meal.recipeId)).toBe(true);
  await page.locator(".meal-card__main").first().click();
  await expect(page.getByTestId("association-notice")).toBeVisible();
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await expect(page.getByTestId("recipe-portions")).toHaveText("3");
  await page.getByRole("button", { name: "Retour", exact: true }).click();
  await page.getByRole("button", { name: "Courses", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Liste de courses", exact: true })).toBeVisible();
});


test("a complete meal is saved, restored and deleted without modifying the week", async ({ page }) => {
  await fresh(page); await library(page);
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Cabillaud en papillote de chou et fenouil");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await page.getByTestId("flow-current").getByTestId("compose-meal").click();
  const builder = page.getByTestId("flow-current");
  await builder.getByTestId("meal-builder-candidate-r824").click();
  await builder.getByTestId("meal-builder-candidate-r1017").click();
  await page.getByRole("button", { name: "Enregistrer mon repas", exact: true }).click();
  await expect(page.getByRole("dialog", { name: "Votre repas", exact: true })).toContainText("Repas enregistré sur cet appareil");
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!).savedMeals.length)).toBe(1);
  await page.reload(); await library(page);
  await page.getByText("Mes repas enregistrés · 1", { exact: true }).click();
  await page.getByRole("button", { name: "Nommer", exact: true }).click();
  await page.getByRole("dialog", { name: "Nommer mon repas" }).getByLabel("Nom du repas", { exact: true }).fill("Dîner du dimanche");
  await page.getByRole("button", { name: "Enregistrer le nom", exact: true }).click();
  await page.getByLabel("Rechercher dans mes repas", { exact: true }).fill("introuvable");
  await expect(page.getByText("Aucun repas trouvé.", { exact: false })).toBeVisible();
  await page.getByLabel("Rechercher dans mes repas", { exact: true }).fill("dimanche");
  await expect(page.getByRole("heading", { name: "Dîner du dimanche", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Ouvrir", exact: true }).click();
  await page.getByRole("button", { name: "Voir mon repas, 3 recettes sur 3", exact: true }).click();
  const summary = page.getByRole("dialog", { name: "Votre repas", exact: true });
  await expect(summary).toContainText("Associations orange présentes");
  await expect(summary.getByTestId("meal-builder-slot-dessert")).toContainText("avocat et banane");
  await summary.getByRole("button", { name: "Enregistrer mon repas", exact: true }).click();
  await expect(summary).toContainText("déjà enregistré");
  await summary.getByRole("button", { name: "Fermer « Votre repas »" }).click();
  await page.getByTestId("flow-current").getByRole("button", { name: "Recette", exact: true }).click();
  const remove = page.getByRole("button", { name: /Supprimer le repas Dîner du dimanche/ });
  if (!await remove.isVisible()) await page.getByText("Mes repas enregistrés · 1", { exact: true }).click();
  await remove.click();
  await expect(page.getByText("Mes repas enregistrés · 0", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Annuler la suppression", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Dîner du dimanche", exact: true })).toBeVisible();
  await page.reload(); await library(page);
  await page.getByText("Mes repas enregistrés · 1", { exact: true }).click();
  await expect(page.getByRole("heading", { name: "Dîner du dimanche", exact: true })).toBeVisible();
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!));
  expect(state.currentPlan).toBeNull();
});

test("plan a complete meal and keep its dessert in shopping after reload", async ({ page }, info) => {
  await fresh(page);
  await page.getByRole("button", { name: "Ajuster mon profil" }).click();
  await page.getByLabel("Temps actif maximum en cuisine (min)", { exact: true }).fill("90");
  await page.getByRole("button", { name: "Enregistrer mon profil" }).click();
  await library(page);
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Cabillaud en papillote de chou et fenouil");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await page.getByTestId("flow-current").getByTestId("compose-meal").click();
  await page.getByTestId("flow-current").getByTestId("meal-builder-candidate-r824").click();
  await page.getByTestId("flow-current").getByTestId("meal-builder-candidate-r1017").click();
  await page.getByRole("button", { name: "Planifier ce repas", exact: true }).click();
  await page.getByRole("button", { name: "Créer la semaine et choisir le jour", exact: true }).click();
  await page.getByLabel("Personnes pour ce repas", { exact: true }).selectOption("3");
  await page.getByTestId("plan-slot-0-lunch").click();
  await expect(page.getByTestId("week-view")).toBeVisible();
  await expect.poll(() => page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!).composedRecipes.length)).toBe(1);
  await page.reload();
  await page.getByRole("button", { name: "Semaine", exact: true }).click();
  const state = await page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!));
  const meal = state.currentPlan.meals.find((item: any) => item.recipeId === state.composedRecipes[0].id);
  expect(meal.portions).toBe(3);
  expect(state.composedRecipes[0].composition.dessert).toBe("r824");
  await page.getByRole("button", { name: /^Lun\. / }).click();
  await page.locator(".meal-card__main").filter({ hasText: "Cabillaud en papillote de chou et fenouil" }).click();
  await page.getByRole("button", { name: "Ajouter une portion", exact: true }).click();
  await expect(page.getByTestId("recipe-portions")).toHaveText("4");
  await page.getByRole("button", { name: "Modifier l’entrée, le plat ou le dessert", exact: true }).click();
  await page.getByTestId("flow-current").getByTestId("meal-builder-candidate-r830").click();
  await expect(page.getByRole("dialog", { name: "Votre repas", exact: true })).toContainText("Associations orange présentes");
  await page.getByRole("button", { name: "Enregistrer les modifications du repas", exact: true }).click();
  await expect(page.getByTestId("week-view")).toBeVisible();
  const changed = await page.evaluate(() => JSON.parse(localStorage.getItem("inflamm-menu:app-state")!));
  const updated = changed.currentPlan.meals.find((item: any) => item.id === meal.id);
  expect(updated.portions).toBe(4); expect(updated.dayIndex).toBe(0); expect(updated.mealType).toBe("lunch");
  expect(updated.recipeId).toContain("r830");
  await expect(page.getByTestId("week-view").getByLabel("Composition du repas")).toContainText("Figues fraîches farcies à la banane écrasée");
  await expect(page.getByTestId("week-view").getByLabel("Composition du repas")).toContainText("Barquettes croquantes");
  await page.getByTestId("flow-current").getByRole("navigation", { name: "Navigation principale" }).getByRole("button", { name: "Courses", exact: true }).click();
  await expect(page.getByTestId("courses-view")).toContainText(/banane/i);
  await page.screenshot({ path: info.outputPath("courses-repas-complet.png"), fullPage: true });
});

test("a recipe issue can be prepared as a local file", async ({ page }) => {
  await fresh(page); await library(page);
  await page.getByLabel("Rechercher une recette", { exact: true }).fill("Cabillaud en papillote de chou et fenouil");
  await expect(page.locator(".catalogue-card")).toHaveCount(1);
  await page.locator(".catalogue-card").click();
  await page.getByRole("button", { name: "Signaler un problème sur cette recette", exact: true }).click();
  await expect(page.getByRole("button", { name: "Télécharger le signalement", exact: true })).toBeDisabled();
  await page.getByLabel("Type de problème").selectOption("Durée");
  await page.getByLabel("Votre observation").fill("La cuisson a demandé cinq minutes de plus.");
  const pending = page.waitForEvent("download");
  await page.getByRole("button", { name: "Télécharger le signalement", exact: true }).click();
  const download = await pending;
  expect(download.suggestedFilename()).toBe("signalement-r711.txt");
  await expect(page.getByRole("dialog", { name: "Préparer un signalement", exact: true })).toContainText("Il reste à le transmettre");
});
