import type {
  Ingredient,
  IngredientCategory,
  IngredientUnit,
  Nutrition,
  Recipe,
} from "./domain.ts";
import { IMPORTED_PLAN_RECIPES } from "./planner-catalog.ts";
import { canonicalIngredientId, shoppingRuleFor } from "./shopping.ts";

type IngredientReference = {
  name: string;
  category: IngredientCategory;
  allergens?: readonly string[];
};

/** Single source of truth for ingredient labels, categories and allergens. */
const INGREDIENTS = {
  oats: { name: "flocons d’avoine", category: "grocery", allergens: ["gluten"] },
  blueberry: { name: "myrtilles", category: "fruit-vegetable" },
  strawberry: { name: "fraises", category: "fruit-vegetable" },
  raspberry: { name: "framboises", category: "fruit-vegetable" },
  walnut: { name: "noix", category: "grocery", allergens: ["fruits-a-coque"] },
  almond: { name: "amandes", category: "grocery", allergens: ["fruits-a-coque"] },
  almond_drink: { name: "boisson à l’amande", category: "beverage", allergens: ["fruits-a-coque"] },
  soy_drink: { name: "boisson au soja", category: "beverage", allergens: ["soja"] },
  yogurt: { name: "yaourt nature", category: "fresh", allergens: ["lait"] },
  kefir: { name: "kéfir nature", category: "fresh", allergens: ["lait"] },
  ricotta: { name: "ricotta", category: "fresh", allergens: ["lait"] },
  goat_cheese: { name: "fromage de chèvre", category: "fresh", allergens: ["lait"] },
  apple: { name: "pomme", category: "fruit-vegetable" },
  pear: { name: "poire", category: "fruit-vegetable" },
  banana: { name: "banane", category: "fruit-vegetable" },
  lemon: { name: "citron", category: "fruit-vegetable" },
  orange: { name: "orange", category: "fruit-vegetable" },
  avocado: { name: "avocat", category: "fruit-vegetable" },
  tomato: { name: "tomate", category: "fruit-vegetable" },
  cherry_tomato: { name: "tomates cerises", category: "fruit-vegetable" },
  cucumber: { name: "concombre", category: "fruit-vegetable" },
  carrot: { name: "carotte", category: "fruit-vegetable" },
  zucchini: { name: "courgette", category: "fruit-vegetable" },
  eggplant: { name: "aubergine", category: "fruit-vegetable" },
  bell_pepper: { name: "poivron", category: "fruit-vegetable" },
  broccoli: { name: "brocoli", category: "fruit-vegetable" },
  spinach: { name: "épinards", category: "fruit-vegetable" },
  mushroom: { name: "champignons", category: "fruit-vegetable" },
  green_bean: { name: "haricots verts", category: "fruit-vegetable" },
  fennel: { name: "fenouil", category: "fruit-vegetable" },
  beet: { name: "betterave cuite", category: "fruit-vegetable" },
  sweet_potato: { name: "patate douce", category: "fruit-vegetable" },
  potato: { name: "pomme de terre", category: "fruit-vegetable" },
  squash: { name: "courge", category: "fruit-vegetable" },
  leek: { name: "poireau", category: "fruit-vegetable" },
  onion: { name: "oignon", category: "fruit-vegetable" },
  garlic: { name: "ail", category: "fruit-vegetable" },
  parsley: { name: "persil", category: "fruit-vegetable" },
  basil: { name: "basilic", category: "fruit-vegetable" },
  mint: { name: "menthe", category: "fruit-vegetable" },
  dill: { name: "aneth", category: "fruit-vegetable" },
  egg: { name: "œuf", category: "fresh", allergens: ["oeuf"] },
  tofu: { name: "tofu ferme", category: "fresh", allergens: ["soja"] },
  chicken: { name: "blanc de poulet", category: "meat-fish" },
  turkey: { name: "dinde", category: "meat-fish" },
  salmon: { name: "saumon", category: "meat-fish", allergens: ["poisson"] },
  trout: { name: "truite", category: "meat-fish", allergens: ["poisson"] },
  sardine: { name: "sardines", category: "meat-fish", allergens: ["poisson"] },
  mackerel: { name: "maquereau", category: "meat-fish", allergens: ["poisson"] },
  tuna: { name: "thon au naturel", category: "meat-fish", allergens: ["poisson"] },
  cod: { name: "cabillaud", category: "meat-fish", allergens: ["poisson"] },
  sea_bass: { name: "bar", category: "meat-fish", allergens: ["poisson"] },
  mussel: { name: "moules", category: "meat-fish", allergens: ["mollusques"] },
  green_lentil: { name: "lentilles vertes cuites", category: "grocery" },
  red_lentil: { name: "lentilles corail", category: "grocery" },
  chickpea: { name: "pois chiches cuits", category: "grocery" },
  white_bean: { name: "haricots blancs cuits", category: "grocery" },
  kidney_bean: { name: "haricots rouges cuits", category: "grocery" },
  quinoa: { name: "quinoa cru", category: "grocery" },
  brown_rice: { name: "riz complet cru", category: "grocery" },
  barley: { name: "orge perlé cru", category: "grocery", allergens: ["gluten"] },
  farro: { name: "épeautre cru", category: "grocery", allergens: ["gluten"] },
  millet: { name: "millet cru", category: "grocery" },
  buckwheat_flour: { name: "farine de sarrasin", category: "grocery" },
  wholewheat_pasta: { name: "pâtes complètes crues", category: "grocery", allergens: ["gluten"] },
  wholewheat_couscous: { name: "semoule complète crue", category: "grocery", allergens: ["gluten"] },
  wholegrain_bread: { name: "pain complet", category: "bakery", allergens: ["gluten"] },
  wholegrain_wrap: { name: "galette complète", category: "bakery", allergens: ["gluten"] },
  wholewheat_lasagna: { name: "feuilles de lasagnes complètes", category: "grocery", allergens: ["gluten"] },
  chia: { name: "graines de chia", category: "grocery" },
  sesame: { name: "graines de sésame", category: "grocery", allergens: ["sesame"] },
  pumpkin_seed: { name: "graines de courge", category: "grocery" },
  hummus: { name: "houmous", category: "fresh", allergens: ["sesame"] },
  olive: { name: "olives", category: "grocery" },
  olive_oil: { name: "huile d’olive", category: "grocery" },
  coconut_milk: { name: "lait de coco", category: "grocery" },
  crushed_tomato: { name: "tomates concassées", category: "grocery" },
  cocoa: { name: "cacao non sucré", category: "grocery" },
  cinnamon: { name: "cannelle", category: "grocery" },
  turmeric: { name: "curcuma", category: "grocery" },
  cumin: { name: "cumin", category: "grocery" },
  paprika: { name: "paprika", category: "grocery" },
  ginger: { name: "gingembre", category: "fruit-vegetable" },
  mustard: { name: "moutarde", category: "grocery", allergens: ["moutarde"] },
  balsamic: { name: "vinaigre balsamique", category: "grocery" },
  vegetable_stock: { name: "bouillon de légumes", category: "grocery" },
} as const satisfies Record<string, IngredientReference>;

type IngredientId = keyof typeof INGREDIENTS;

function ingredient(id: IngredientId, quantity: number, unit: IngredientUnit): Ingredient {
  const reference: IngredientReference = INGREDIENTS[id];
  return {
    id: canonicalIngredientId(id),
    name: reference.name,
    quantity,
    unit,
    category: reference.category,
    ...(reference.allergens ? { allergens: reference.allergens } : {}),
    ...(shoppingRuleFor(id)?.pantry_staple === true ? { pantryStaple: true } : {}),
  };
}

const NUTRITION_NOTE = "Valeurs nutritionnelles estimatives par portion, à titre indicatif." as const;

function nutrition(calories: number, protein: number, fiber: number): Nutrition {
  return { calories, protein, fiber, estimated: true, note: NUTRITION_NOTE };
}

const ALL_YEAR = ["all-year"] as const;
const VEGETARIAN = ["classic", "vegetarian", "no-pork"] as const;
const NO_PORK = ["classic", "no-pork"] as const;

const BASE_RECIPE_SOURCE: readonly Recipe[] = [
  {
    id: "overnight-oats-myrtilles-noix",
    title: "Overnight oats aux myrtilles et noix",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 8, restMinutes: 480, costPerPortion: 1.7,
    seasons: ALL_YEAR, equipment: [], allergens: ["gluten", "fruits-a-coque"],
    tags: ["cereale-complete", "fruit", "sans-cuisson"],
    ingredients: [ingredient("oats", 50, "g"), ingredient("almond_drink", 140, "ml"), ingredient("blueberry", 80, "g"), ingredient("chia", 10, "g"), ingredient("walnut", 15, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(405, 11, 10), description: "Un petit-déjeuner préparé la veille, fruité et rassasiant.",
    steps: ["Mélanger les flocons, le chia, la cannelle et la boisson végétale.", "Réserver une nuit au frais.", "Ajouter les myrtilles et les noix au moment de servir."],
    conservation: "24 heures au réfrigérateur dans un récipient fermé.", image: "/assets/recipes/overnight-oats-myrtilles-noix.jpg",
  },
  {
    id: "yaourt-pomme-amandes",
    title: "Yaourt, pomme et amandes à la cannelle",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 6, costPerPortion: 1.45,
    seasons: ["autumn", "winter", "all-year"], equipment: [], allergens: ["lait", "fruits-a-coque"], tags: ["rapide", "fruit"],
    ingredients: [ingredient("yogurt", 150, "g"), ingredient("apple", 1, "piece"), ingredient("almond", 20, "g"), ingredient("oats", 30, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(350, 14, 7), description: "Un bol croquant qui associe fruit frais, céréales et produit laitier.",
    steps: ["Couper la pomme en petits dés.", "Verser le yaourt dans un bol et ajouter les flocons.", "Terminer avec la pomme, les amandes et la cannelle."],
    conservation: "À assembler juste avant dégustation.", image: "/assets/recipes/yaourt-pomme-amandes.jpg",
  },
  {
    id: "tartine-avocat-tomate-oeuf",
    title: "Tartine avocat, tomate et œuf",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 12, costPerPortion: 2.25,
    seasons: ["spring", "summer"], equipment: ["hob", "toaster"], allergens: ["gluten", "oeuf"], tags: ["cereale-complete", "vegetarien"],
    ingredients: [ingredient("wholegrain_bread", 70, "g"), ingredient("avocado", 0.5, "piece"), ingredient("tomato", 0.5, "piece"), ingredient("egg", 1, "piece"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 0.5, "c_cafe")],
    nutrition: nutrition(390, 15, 9), description: "Une tartine complète, fraîche et généreuse.",
    steps: ["Plonger l’œuf dans une casserole d’eau frémissante et cuire 7 minutes. Le refroidir sous l’eau froide puis l’écaler ; pour un jaune complètement pris, prolonger à 9–10 minutes.","Écraser l’avocat avec le jus du citron et l’huile prévue. Faire griller le pain.","Tartiner le pain d’avocat, puis garnir de tomate en tranches et d’œuf coupé en quartiers."],
    conservation: "À consommer immédiatement après assemblage.", image: "/assets/recipes/tartine-avocat-tomate-oeuf.jpg",
  },
  {
    id: "pudding-chia-poire-cacao",
    title: "Pudding de chia, poire et cacao",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 7, restMinutes: 180, costPerPortion: 1.55,
    seasons: ["autumn", "winter"], equipment: [], allergens: ["soja"], tags: ["sans-gluten", "sans-cuisson", "fruit"],
    ingredients: [ingredient("chia", 30, "g"), ingredient("soy_drink", 180, "ml"), ingredient("pear", 1, "piece"), ingredient("cocoa", 1, "c_cafe"), ingredient("pumpkin_seed", 10, "g")],
    nutrition: nutrition(330, 12, 13), description: "Une crème de chia cacaotée adoucie par la poire.",
    steps: ["Mélanger le chia, le cacao et la boisson au soja.", "Laisser épaissir au moins 3 heures au frais.", "Ajouter la poire en dés et les graines de courge."],
    conservation: "Jusqu’à 2 jours au réfrigérateur.", image: "/assets/recipes/pudding-chia-poire-cacao.jpg",
  },
  {
    id: "porridge-millet-pomme",
    title: "Porridge de millet à la pomme",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 22, costPerPortion: 1.35,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["fruits-a-coque"], tags: ["sans-gluten", "chaud", "fruit"],
    ingredients: [ingredient("millet", 55, "g"), ingredient("almond_drink", 220, "ml"), ingredient("apple", 1, "piece"), ingredient("walnut", 15, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(415, 10, 8), description: "Un porridge chaud au millet pour changer de l’avoine.",
    steps: ["Rincer le millet, puis le cuire à feu doux dans la boisson végétale, en remuant régulièrement, selon la durée indiquée sur le paquet et jusqu’à ce que les grains soient tendres.","Laver la pomme, retirer le cœur et la râper. Incorporer la moitié en fin de cuisson.","Servir avec le reste de pomme râpée, les noix et la cannelle."],
    conservation: "2 jours au frais; réchauffer avec un peu de boisson végétale.", image: "/assets/recipes/porridge-millet-pomme.jpg",
  },
  {
    id: "smoothie-kefir-fruits-rouges",
    title: "Smoothie kéfir et fruits rouges",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 5, costPerPortion: 1.85,
    seasons: ["spring", "summer"], equipment: ["blender"], allergens: ["lait", "gluten"], tags: ["rapide", "fruit"],
    ingredients: [ingredient("kefir", 180, "ml"), ingredient("strawberry", 80, "g"), ingredient("raspberry", 50, "g"), ingredient("banana", 0.5, "piece"), ingredient("oats", 25, "g"), ingredient("ginger", 5, "g")],
    nutrition: nutrition(285, 11, 7), description: "Un smoothie acidulé et consistant, prêt en quelques minutes.",
    steps: ["Laver et équeuter les fraises. Peler la banane et le gingembre, puis les couper en petits morceaux.","Mixer tous les ingrédients jusqu’à obtenir une texture lisse.","Servir sans attendre."],
    conservation: "À boire le jour même, idéalement juste après mixage.", image: "/assets/recipes/smoothie-kefir-fruits-rouges.jpg",
  },
  {
    id: "galette-sarrasin-epinards-ricotta",
    title: "Galette de sarrasin, épinards et ricotta",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.1,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["oeuf", "lait"], tags: ["sans-gluten", "vegetarien"],
    ingredients: [ingredient("buckwheat_flour", 55, "g"), ingredient("egg", 1, "piece"), ingredient("spinach", 80, "g"), ingredient("ricotta", 45, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(365, 18, 6), description: "Une galette salée souple, garnie de verdure et de ricotta.",
    steps: ["Battre l’œuf. Délayer la farine avec 100 ml d’eau par portion et la moitié de l’œuf battu.","Chauffer une poêle antiadhésive avec la moitié de l’huile et cuire la galette des deux côtés, jusqu’à ce que la pâte soit prise. Réserver.","Faire tomber les épinards avec le reste de l’huile, puis ajouter le reste d’œuf et le cuire en remuant jusqu’à ce qu’il soit complètement pris.","Mélanger la ricotta avec le jus du citron, puis garnir la galette avec cette préparation et les épinards à l’œuf."],
    conservation: "La galette et la garniture se gardent séparément 24 heures au frais.", image: "/assets/recipes/galette-sarrasin-epinards-ricotta.jpg",
  },
  {
    id: "tofu-brouille-champignons",
    title: "Tofu brouillé aux champignons",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 15, costPerPortion: 2.05,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["soja", "gluten"], tags: ["vegetarien", "rapide"],
    ingredients: [ingredient("tofu", 140, "g"), ingredient("mushroom", 100, "g"), ingredient("spinach", 50, "g"), ingredient("wholegrain_bread", 50, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("turmeric", 0.5, "c_cafe")],
    nutrition: nutrition(360, 25, 7), description: "Une assiette salée végétarienne, fondante et rapide.",
    steps: ["Émincer les champignons et les faire dorer dans l’huile prévue.","Émietter le tofu, ajouter le curcuma et cuire 5 minutes en remuant.","Incorporer les épinards et poursuivre jusqu’à ce qu’ils soient tombés. Servir avec le pain grillé."],
    conservation: "2 jours au réfrigérateur sans le pain.", image: "/assets/recipes/tofu-brouille-champignons.jpg",
  },
  {
    id: "salade-lentilles-noix",
    title: "Salade de lentilles, légumes et noix",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 18, costPerPortion: 2.35,
    seasons: ALL_YEAR, equipment: [], allergens: ["fruits-a-coque", "moutarde"], tags: ["legumineuse", "sans-gluten", "meal-prep"],
    ingredients: [ingredient("green_lentil", 180, "g"), ingredient("carrot", 70, "g"), ingredient("cucumber", 80, "g"), ingredient("walnut", 20, "g"), ingredient("parsley", 10, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(460, 19, 16), description: "Une salade de lentilles croquante, facile à emporter.",
    steps: ["Laver et couper finement la carotte et le concombre, puis hacher le persil.","Mélanger la moutarde et l’huile pour préparer la vinaigrette.","Réunir les lentilles cuites égouttées, les légumes et le persil. Assaisonner avec la vinaigrette et ajouter les noix au moment de servir."],
    conservation: "3 jours au réfrigérateur; ajouter les noix au dernier moment.", image: "/assets/recipes/salade-lentilles-noix.jpg",
  },
  {
    id: "bowl-quinoa-legumes-houmous",
    title: "Bowl quinoa, légumes rôtis et houmous",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 3.05,
    seasons: ["summer", "autumn"], equipment: ["hob", "oven"], allergens: ["sesame"], tags: ["cereale-complete", "vegetarien", "meal-prep"],
    ingredients: [ingredient("quinoa", 70, "g"), ingredient("zucchini", 120, "g"), ingredient("bell_pepper", 100, "g"), ingredient("chickpea", 80, "g"), ingredient("hummus", 45, "g"), ingredient("olive_oil", 1, "c_soupe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(555, 19, 13), description: "Un bol coloré avec quinoa, légumes dorés et houmous crémeux.",
    steps: ["Préchauffer le four à 210 °C. Couper la courgette et le poivron épépiné en petits morceaux, les mélanger avec l’huile et les rôtir environ 20 minutes, jusqu’à tendreté.","Pendant ce temps, rincer et cuire le quinoa selon les indications du paquet, puis l’égoutter si nécessaire et l’égrainer.","Assembler le quinoa, les légumes rôtis, les pois chiches cuits égouttés et le houmous. Arroser avec le jus du citron."],
    conservation: "3 jours au frais, houmous conservé séparément.", image: "/assets/recipes/bowl-quinoa-legumes-houmous.jpg",
  },
  {
    id: "salade-haricots-blancs-tomates",
    title: "Salade de haricots blancs aux tomates",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 12, costPerPortion: 2.15,
    seasons: ["spring", "summer"], equipment: [], allergens: [], tags: ["legumineuse", "sans-gluten", "rapide"],
    ingredients: [ingredient("white_bean", 190, "g"), ingredient("cherry_tomato", 120, "g"), ingredient("cucumber", 90, "g"), ingredient("olive", 25, "g"), ingredient("basil", 8, "g"), ingredient("olive_oil", 1, "c_soupe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(410, 17, 14), description: "Une salade méditerranéenne économique et sans cuisson.",
    steps: ["Rincer et égoutter les haricots.","Couper les tomates, le concombre et les olives.","Mélanger avec le basilic, le jus du citron et l’huile."],
    conservation: "2 jours au réfrigérateur dans une boîte hermétique.", image: "/assets/recipes/salade-haricots-blancs-tomates.jpg",
  },
  {
    id: "taboule-pois-chiches-complet",
    title: "Taboulé complet aux pois chiches",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.25,
    seasons: ["spring", "summer"], equipment: ["hob"], allergens: ["gluten"], tags: ["legumineuse", "cereale-complete", "meal-prep"],
    ingredients: [ingredient("wholewheat_couscous", 65, "g"), ingredient("chickpea", 120, "g"), ingredient("tomato", 1, "piece"), ingredient("cucumber", 80, "g"), ingredient("parsley", 12, "g"), ingredient("mint", 6, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(505, 18, 13), description: "Un taboulé généreux en herbes, céréales complètes et pois chiches.",
    steps: ["Réhydrater la semoule complète avec la quantité d’eau bouillante et pendant la durée indiquées sur le paquet, puis l’égrainer et la laisser tiédir.","Laver et détailler les légumes, puis ciseler le persil et la menthe.","Mélanger la semoule avec les légumes, les herbes et les pois chiches cuits égouttés. Ajouter le jus du citron et l’huile."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/taboule-pois-chiches-complet.jpg",
  },
  {
    id: "pates-completes-ratatouille",
    title: "Pâtes complètes à la ratatouille",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.3,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: ["gluten"], tags: ["cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("wholewheat_pasta", 80, "g"), ingredient("eggplant", 90, "g"), ingredient("zucchini", 90, "g"), ingredient("bell_pepper", 70, "g"), ingredient("crushed_tomato", 130, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("basil", 6, "g")],
    nutrition: nutrition(480, 17, 12), description: "Des pâtes complètes enrobées d’une ratatouille fondante.",
    steps: ["Couper l’aubergine, la courgette et le poivron épépiné en petits dés. Les faire revenir avec l’ail haché et l’huile pendant environ 5 minutes.","Ajouter les tomates concassées et laisser mijoter 15 à 20 minutes, jusqu’à ce que l’aubergine soit tendre. Pendant ce temps, cuire les pâtes selon les indications du paquet.","Mélanger les pâtes égouttées à la sauce et ajouter le basilic ciselé."],
    conservation: "3 jours au réfrigérateur; réchauffer doucement.", image: "/assets/recipes/pates-completes-ratatouille.jpg",
  },
  {
    id: "salade-sardines-pommes-terre-haricots",
    title: "Salade de sardines, pommes de terre et haricots verts",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.15,
    seasons: ["spring", "summer"], equipment: ["hob"], allergens: ["poisson", "moutarde"], tags: ["poisson-gras", "sans-gluten"],
    ingredients: [ingredient("sardine", 100, "g"), ingredient("potato", 180, "g"), ingredient("green_bean", 120, "g"), ingredient("cherry_tomato", 80, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(515, 31, 9), description: "Une salade tiède complète au poisson gras.",
    steps: ["Peler les pommes de terre et les couper en petits morceaux. Les cuire dans l’eau frémissante 15 à 20 minutes, jusqu’à tendreté ; ajouter les haricots verts équeutés pendant les 10 à 12 dernières minutes, puis égoutter.","Utiliser des sardines cuites : égoutter celles en conserve ; si elles sont fraîches, les désarêter et cuire les filets dans une poêle antiadhésive jusqu’à 63 °C à cœur, puis les laisser tiédir.","Mélanger la moutarde avec le jus du citron et l’huile. Couper les tomates cerises.","Assembler les légumes tièdes, les tomates et les sardines, puis ajouter la vinaigrette juste avant de servir."],
    conservation: "24 heures au réfrigérateur; conserver la vinaigrette à part.", image: "/assets/recipes/salade-sardines-pommes-terre-haricots.jpg",
  },
  {
    id: "salade-thon-haricots-rouges",
    title: "Salade de thon et haricots rouges",
    mealTypes: ["lunch"], diet: NO_PORK, prepMinutes: 12, costPerPortion: 2.8,
    seasons: ALL_YEAR, equipment: [], allergens: ["poisson"], tags: ["poisson-maigre", "legumineuse", "rapide"],
    ingredients: [ingredient("tuna", 100, "g"), ingredient("kidney_bean", 150, "g"), ingredient("tomato", 1, "piece"), ingredient("bell_pepper", 70, "g"), ingredient("onion", 30, "g"), ingredient("parsley", 8, "g"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(440, 38, 12), description: "Une salade express riche en textures et facile à emporter.",
    steps: ["Rincer les haricots et égoutter le thon.","Émincer les légumes et le persil.","Tout mélanger avec le jus du citron et l’huile."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/salade-thon-haricots-rouges.jpg",
  },
  {
    id: "bowl-saumon-riz-complet-avocat",
    title: "Bowl saumon, riz complet et avocat",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 4.75,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["poisson", "sesame"], tags: ["poisson-gras", "cereale-complete"],
    ingredients: [ingredient("salmon", 120, "g"), ingredient("brown_rice", 70, "g"), ingredient("avocado", 0.5, "piece"), ingredient("cucumber", 80, "g"), ingredient("carrot", 60, "g"), ingredient("sesame", 8, "g"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(650, 36, 10), description: "Un bowl complet au saumon poêlé et aux légumes croquants.",
    steps: ["Cuire le riz complet selon les indications du paquet, puis l’égoutter et le laisser tiédir.","Pendant la cuisson du riz, cuire le saumon dans une poêle antiadhésive jusqu’à 63 °C à cœur. Laver et tailler le concombre et la carotte.","Prélever et couper la chair d’avocat au dernier moment. Assembler avec le riz, le saumon et les légumes, arroser du jus du citron et parsemer de sésame."],
    conservation: "24 heures au réfrigérateur sans l’avocat, à ajouter au service.", image: "/assets/recipes/bowl-saumon-riz-complet-avocat.jpg",
  },
  {
    id: "bowl-poulet-orge-legumes",
    title: "Bowl de poulet, orge et légumes",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 3.35,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["gluten", "moutarde"], tags: ["volaille", "cereale-complete", "meal-prep"],
    ingredients: [ingredient("chicken", 130, "g"), ingredient("barley", 65, "g"), ingredient("broccoli", 110, "g"), ingredient("carrot", 70, "g"), ingredient("spinach", 50, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(545, 45, 11), description: "Un bowl de volaille, orge moelleuse et légumes verts.",
    steps: ["Cuire l’orge dans l’eau frémissante selon les indications du paquet, puis l’égoutter.","Pendant ce temps, couper le poulet en lanières et le poêler avec la moitié de l’huile jusqu’à 74 °C à cœur. Cuire le brocoli en petits bouquets et la carotte en fines rondelles à la vapeur ou dans l’eau frémissante jusqu’à tendreté ; ajouter les épinards en fin de cuisson.","Mélanger la moutarde avec le reste de l’huile. Assembler l’orge, le poulet et les légumes, puis les enrober de cet assaisonnement."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/bowl-poulet-orge-legumes.jpg",
  },
  {
    id: "wrap-dinde-crudites-houmous",
    title: "Wrap complet de dinde, crudités et houmous",
    mealTypes: ["lunch"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.05,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["gluten", "sesame"], tags: ["volaille", "rapide", "a-emporter"],
    ingredients: [ingredient("wholegrain_wrap", 1, "piece"), ingredient("turkey", 100, "g"), ingredient("hummus", 40, "g"), ingredient("carrot", 60, "g"), ingredient("cucumber", 70, "g"), ingredient("spinach", 35, "g"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(475, 35, 9), description: "Un wrap frais, pratique et généreusement garni.",
    steps: ["Couper la dinde en fines lanières et la cuire dans une poêle antiadhésive à feu modéré, jusqu’à 74 °C à cœur. La laisser tiédir sur une assiette propre.","Étaler le houmous sur la galette. Ajouter la dinde cuite, la carotte et le concombre finement taillés ainsi que les épinards lavés et essorés.","Arroser avec le jus du citron, rouler serré et couper en deux."],
    conservation: "24 heures au frais, bien emballé.", image: "/assets/recipes/wrap-dinde-crudites-houmous.jpg",
  },
  {
    id: "bowl-cabillaud-patate-douce",
    title: "Bowl de cabillaud et patate douce",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 40, costPerPortion: 4.1,
    seasons: ALL_YEAR, equipment: ["oven"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten"],
    ingredients: [ingredient("cod", 140, "g"), ingredient("sweet_potato", 180, "g"), ingredient("broccoli", 110, "g"), ingredient("spinach", 45, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("paprika", 0.5, "c_cafe")],
    nutrition: nutrition(470, 38, 11), description: "Un bowl au cabillaud rôti, doux et coloré.",
    steps: ["Préchauffer le four à 210 °C. Couper la patate douce en petits cubes, les mélanger avec la moitié de l’huile et les rôtir 20 minutes.","Ajouter le brocoli en petits bouquets et le cabillaud désarêté, enrobés du reste de l’huile et du paprika. Poursuivre environ 10 minutes, jusqu’à tendreté des légumes et 63 °C à cœur du poisson ; prolonger si nécessaire.","Servir sur les épinards lavés et essorés avec le jus du citron."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/bowl-cabillaud-patate-douce.jpg",
  },
  {
    id: "mijote-aubergine-pois-chiches",
    title: "Mijoté d’aubergine et pois chiches",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 2.2,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("eggplant", 180, "g"), ingredient("chickpea", 160, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("cumin", 0.5, "c_cafe"), ingredient("parsley", 8, "g")],
    nutrition: nutrition(430, 16, 15), description: "Un plat mijoté végétarien aux saveurs méditerranéennes.",
    steps: ["Hacher l’oignon et l’ail, couper l’aubergine en petits dés, puis les faire revenir dans l’huile pendant environ 5 minutes.","Ajouter les tomates, les pois chiches cuits égouttés et le cumin. Laisser mijoter environ 18 minutes, jusqu’à ce que l’aubergine soit tendre.","Parsemer de persil haché avant de servir."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/mijote-aubergine-pois-chiches.jpg",
  },
  {
    id: "salade-betterave-chevre-lentilles",
    title: "Salade de betterave, chèvre et lentilles",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 14, costPerPortion: 2.65,
    seasons: ["autumn", "winter", "spring"], equipment: [], allergens: ["lait", "fruits-a-coque"], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("green_lentil", 160, "g"), ingredient("beet", 140, "g"), ingredient("goat_cheese", 45, "g"), ingredient("walnut", 15, "g"), ingredient("spinach", 45, "g"), ingredient("balsamic", 1, "c_soupe"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(455, 22, 13), description: "Une salade terreuse et acidulée, adoucie par le chèvre.",
    steps: ["Couper la betterave cuite et le fromage de chèvre.","Mélanger le vinaigre et l’huile.","Assembler avec les lentilles cuites égouttées, les épinards lavés et les noix. Ajouter l’assaisonnement juste avant de servir."],
    conservation: "2 jours au réfrigérateur, assaisonnement séparé.", image: "/assets/recipes/salade-betterave-chevre-lentilles.jpg",
  },
  {
    id: "salade-maquereau-betterave-pomme-terre",
    title: "Salade de maquereau, betterave et pomme de terre",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.3,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["poisson", "moutarde"], tags: ["poisson-gras", "sans-gluten"],
    ingredients: [ingredient("mackerel", 110, "g"), ingredient("beet", 120, "g"), ingredient("potato", 170, "g"), ingredient("spinach", 45, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("lemon", 0.25, "piece"), ingredient("dill", 5, "g")],
    nutrition: nutrition(530, 32, 8), description: "Une salade hivernale au maquereau et aux légumes racines.",
    steps: ["Peler les pommes de terre, les couper en quartiers et les cuire dans l’eau frémissante 15 à 20 minutes, jusqu’à tendreté. Égoutter et laisser tiédir.","Utiliser du maquereau cuit : égoutter celui en conserve ; s’il est frais, le désarêter et cuire les filets dans une poêle antiadhésive jusqu’à 63 °C à cœur, puis les laisser tiédir.","Mélanger la moutarde, le jus du citron et l’aneth ciselé. Couper la betterave cuite.","Assembler les pommes de terre, la betterave, les épinards lavés et le maquereau, puis ajouter l’assaisonnement."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/salade-maquereau-betterave-pomme-terre.jpg",
  },
  {
    id: "saumon-brocoli-riz-complet",
    title: "Saumon, brocoli et riz complet",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 28, costPerPortion: 4.55,
    seasons: ALL_YEAR, equipment: ["hob", "steamer"], allergens: ["poisson"], tags: ["poisson-gras", "cereale-complete"],
    ingredients: [ingredient("salmon", 140, "g"), ingredient("broccoli", 180, "g"), ingredient("brown_rice", 70, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_cafe"), ingredient("dill", 5, "g")],
    nutrition: nutrition(610, 42, 10), description: "Une assiette simple de saumon, brocoli vapeur et riz complet.",
    steps: ["Cuire le riz complet selon les indications du paquet.","Pendant ce temps, cuire le brocoli en petits bouquets à la vapeur jusqu’à tendreté et poêler le saumon dans une poêle antiadhésive jusqu’à 63 °C à cœur.","Servir avec le jus du citron, l’aneth ciselé et toute l’huile prévue."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/saumon-brocoli-riz-complet.jpg",
  },
  {
    id: "curry-pois-chiches-epinards",
    title: "Curry de pois chiches et épinards",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 24, costPerPortion: 2.4,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("chickpea", 180, "g"), ingredient("spinach", 120, "g"), ingredient("crushed_tomato", 120, "g"), ingredient("coconut_milk", 100, "ml"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("ginger", 5, "g")],
    nutrition: nutrition(480, 17, 14), description: "Un curry végétarien crémeux aux épices douces.",
    steps: ["Hacher l’oignon et l’ail, râper le gingembre. Les faire cuire doucement avec le curcuma et une petite partie du lait de coco, en remuant, jusqu’à ce que l’oignon s’attendrisse.","Ajouter les tomates, le reste du lait de coco et les pois chiches cuits égouttés, puis laisser mijoter 12 minutes.","Ajouter les épinards lavés et poursuivre jusqu’à ce qu’ils soient tombés."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/curry-pois-chiches-epinards.jpg",
  },
  {
    id: "omelette-legumes-quinoa",
    title: "Omelette aux légumes et quinoa",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.45,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["oeuf"], tags: ["vegetarien", "sans-gluten", "anti-gaspi"],
    ingredients: [ingredient("egg", 2, "piece"), ingredient("quinoa", 45, "g"), ingredient("zucchini", 80, "g"), ingredient("mushroom", 70, "g"), ingredient("spinach", 45, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("parsley", 6, "g")],
    nutrition: nutrition(430, 25, 7), description: "Une omelette complète qui accueille facilement les légumes restants.",
    steps: ["Rincer et cuire le quinoa selon les indications du paquet. Pendant ce temps, poêler la courgette en petits dés et les champignons émincés dans l’huile ; ajouter les épinards en fin de cuisson.","Battre les œufs avec le persil haché, puis les verser sur les légumes.","Cuire à feu doux jusqu’à ce que les œufs soient pris au centre et servir avec le quinoa égoutté."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/omelette-legumes-quinoa.jpg",
  },
  {
    id: "truite-haricots-verts-quinoa",
    title: "Truite, haricots verts et quinoa",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 4.25,
    seasons: ALL_YEAR, equipment: ["hob", "steamer"], allergens: ["poisson"], tags: ["poisson-gras", "sans-gluten", "cereale-complete"],
    ingredients: [ingredient("trout", 140, "g"), ingredient("green_bean", 160, "g"), ingredient("quinoa", 65, "g"), ingredient("lemon", 0.5, "piece"), ingredient("dill", 5, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(555, 41, 9), description: "Une assiette légère en apparence, mais complète et rassasiante.",
    steps: ["Rincer et cuire le quinoa selon les indications du paquet. En parallèle, cuire les haricots verts équeutés à la vapeur ou dans l’eau frémissante jusqu’à tendreté.","Cuire la truite dans une poêle antiadhésive, côté peau d’abord, puis la retourner et poursuivre jusqu’à 63 °C à cœur.","Servir avec le jus du citron, l’aneth ciselé et toute l’huile d’olive prévue."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/truite-haricots-verts-quinoa.jpg",
  },
  {
    id: "bowl-tofu-brocoli-sesame",
    title: "Bowl tofu, brocoli et sésame",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 22, costPerPortion: 2.85,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["soja", "sesame"], tags: ["vegetarien", "sans-gluten", "cereale-complete"],
    ingredients: [ingredient("tofu", 150, "g"), ingredient("broccoli", 160, "g"), ingredient("brown_rice", 65, "g"), ingredient("carrot", 60, "g"), ingredient("sesame", 10, "g"), ingredient("ginger", 5, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(540, 29, 11), description: "Un bowl végétarien au tofu doré et au brocoli croquant.",
    steps: ["Cuire le riz complet selon les indications du paquet. Pendant ce temps, couper le brocoli en petits bouquets et la carotte en fines lamelles.","Égoutter et couper le tofu en dés, puis le faire dorer dans l’huile avec le gingembre râpé. Ajouter le brocoli, la carotte et quelques cuillerées d’eau. Couvrir et poursuivre à feu doux jusqu’à tendreté, en remuant régulièrement et en ajoutant un peu d’eau si le fond sèche.","Servir sur le riz égoutté et parsemer de sésame."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/bowl-tofu-brocoli-sesame.jpg",
  },
  {
    id: "cabillaud-tomate-olives",
    title: "Cabillaud mijoté à la tomate et aux olives",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 4.05,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten", "mediterraneen"],
    ingredients: [ingredient("cod", 150, "g"), ingredient("crushed_tomato", 200, "g"), ingredient("olive", 30, "g"), ingredient("zucchini", 120, "g"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("parsley", 6, "g")],
    nutrition: nutrition(360, 38, 7), description: "Un cabillaud tendre dans une sauce tomate aux olives.",
    steps: ["Hacher l’oignon et l’ail, couper la courgette en petits dés, puis les faire revenir dans l’huile.","Ajouter les tomates et les olives, puis laisser mijoter 10 minutes.","Déposer le cabillaud désarêté dans la sauce, couvrir et cuire environ 8 minutes, jusqu’à 63 °C à cœur ; prolonger selon l’épaisseur. Parsemer de persil haché avant de servir."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/cabillaud-tomate-olives.jpg",
  },
  {
    id: "poulet-curcuma-legumes-semoule",
    title: "Poulet au curcuma, légumes et semoule complète",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 28, costPerPortion: 3.35,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["gluten"], tags: ["volaille", "cereale-complete", "batch-cooking"],
    ingredients: [ingredient("chicken", 140, "g"), ingredient("wholewheat_couscous", 65, "g"), ingredient("carrot", 80, "g"), ingredient("zucchini", 100, "g"), ingredient("chickpea", 60, "g"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("cumin", 0.5, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(590, 47, 11), description: "Une assiette de poulet épicé doucement, semoule et légumes.",
    steps: ["Couper le poulet en lanières et le faire dorer dans l’huile avec le curcuma et le cumin.","Ajouter la carotte en fines rondelles, la courgette en petits dés et quelques cuillerées d’eau. Couvrir et cuire à feu doux jusqu’à tendreté des légumes et 74 °C à cœur du poulet ; ajouter un peu d’eau si le fond sèche. Ajouter les pois chiches cuits égouttés en fin de cuisson pour les réchauffer.","Pendant ce temps, réhydrater la semoule avec la quantité d’eau bouillante et pendant la durée indiquées sur le paquet, puis l’égrainer. Servir avec le poulet et les légumes."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/poulet-curcuma-legumes-semoule.jpg",
  },
  {
    id: "boulettes-dinde-courgette-tomate",
    title: "Boulettes de dinde, courgette et tomate",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 3.45,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: ["oeuf"], tags: ["volaille", "sans-gluten"],
    ingredients: [ingredient("turkey", 150, "g"), ingredient("egg", 0.25, "piece"), ingredient("zucchini", 130, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("onion", 40, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("basil", 6, "g")],
    nutrition: nutrition(390, 40, 6), description: "Des boulettes de dinde moelleuses dans une sauce tomate aux courgettes.",
    steps: ["Hacher la dinde si nécessaire. Hacher l’oignon et mélanger sa moitié avec la dinde et la quantité d’œuf battu prévue. Former de petites boulettes régulières.","Faire dorer les boulettes dans la moitié de l’huile, puis les réserver sur une assiette.","Faire revenir le reste de l’oignon, l’ail haché et la courgette en petits dés dans le reste de l’huile. Ajouter les tomates, remettre les boulettes et laisser mijoter à couvert environ 10 minutes, jusqu’à 74 °C au cœur des boulettes ; prolonger si nécessaire.","Ajouter le basilic ciselé avant de servir, avec des ustensiles propres."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/boulettes-dinde-courgette-tomate.jpg",
  },
  {
    id: "bar-four-fenouil-pommes-terre",
    title: "Bar au four, fenouil et pommes de terre",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 60, costPerPortion: 4.8,
    seasons: ["autumn", "winter", "spring"], equipment: ["oven"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten"],
    ingredients: [ingredient("sea_bass", 150, "g"), ingredient("fennel", 140, "g"), ingredient("potato", 180, "g"), ingredient("lemon", 0.5, "piece"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("dill", 5, "g")],
    nutrition: nutrition(475, 37, 8), description: "Un poisson blanc rôti avec fenouil fondant et pommes de terre.",
    steps: ["Préchauffer le four à 190 °C. Couper les pommes de terre en rondelles très fines, les répartir dans un plat avec la moitié de l’huile, couvrir et précuire environ 15 minutes.","Ajouter le fenouil très finement émincé et l’ail haché avec le reste de l’huile. Couvrir et poursuivre environ 15 minutes, jusqu’à ce que les légumes soient tendres.","Déposer le bar désarêté et le citron en tranches sur les légumes. Cuire encore 10 à 15 minutes, jusqu’à tendreté des légumes et 63 °C à cœur du poisson. Ajouter l’aneth ciselé avant de servir."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/bar-four-fenouil-pommes-terre.jpg",
  },
  {
    id: "dal-lentilles-corail-courge",
    title: "Dal de lentilles corail et courge",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 1.95,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten", "batch-cooking"],
    ingredients: [ingredient("red_lentil", 85, "g"), ingredient("squash", 180, "g"), ingredient("coconut_milk", 90, "ml"), ingredient("crushed_tomato", 100, "g"), ingredient("onion", 50, "g"), ingredient("ginger", 5, "g"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("cumin", 0.5, "c_cafe")],
    nutrition: nutrition(475, 19, 15), description: "Un dal doux et velouté aux lentilles corail et à la courge.",
    steps: ["Hacher l’oignon, râper le gingembre et couper la courge en petits dés. Cuire doucement l’oignon, le gingembre et les épices avec une petite partie du lait de coco, en remuant.","Rincer les lentilles. Les ajouter avec la courge, les tomates et 180 ml d’eau par portion. Laisser mijoter à couvert 15 à 20 minutes, en remuant régulièrement et en ajoutant un peu d’eau si le fond sèche.","Verser le reste du lait de coco et poursuivre quelques minutes, jusqu’à ce que les lentilles et la courge soient tendres et la texture crémeuse."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/dal-lentilles-corail-courge.jpg",
  },
  {
    id: "minestrone-haricots-blancs-epeautre",
    title: "Minestrone aux haricots blancs et épeautre",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.15,
    seasons: ["autumn", "winter", "spring"], equipment: ["hob"], allergens: ["gluten"], tags: ["legumineuse", "cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("white_bean", 140, "g"), ingredient("farro", 55, "g"), ingredient("carrot", 70, "g"), ingredient("leek", 70, "g"), ingredient("zucchini", 70, "g"), ingredient("crushed_tomato", 130, "g"), ingredient("vegetable_stock", 350, "ml"), ingredient("basil", 5, "g")],
    nutrition: nutrition(445, 19, 16), description: "Une soupe-repas italienne aux légumes, haricots et épeautre.",
    steps: ["Couper les légumes en petits dés et les faire suer à couvert avec quelques cuillerées du bouillon prévu, en remuant.","Ajouter l’épeautre rincé, les tomates et le reste du bouillon. Laisser mijoter selon la durée indiquée sur le paquet, jusqu’à ce que les grains soient tendres ; ajouter un peu d’eau si nécessaire pour garder une texture de soupe.","Ajouter les haricots blancs cuits égouttés pendant les 5 dernières minutes. Servir avec le basilic ciselé."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/minestrone-haricots-blancs-epeautre.jpg",
  },
  {
    id: "risotto-orge-champignons-epinards",
    title: "Orge crémeuse aux champignons et épinards",
    mealTypes: ["dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.45,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["gluten", "lait"], tags: ["cereale-complete", "vegetarien"],
    ingredients: [ingredient("barley", 80, "g"), ingredient("mushroom", 160, "g"), ingredient("spinach", 80, "g"), ingredient("onion", 45, "g"), ingredient("vegetable_stock", 320, "ml"), ingredient("ricotta", 35, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(455, 18, 12), description: "Une orge façon risotto, crémeuse et riche en champignons.",
    steps: ["Émincer les champignons et l’oignon. Faire dorer les champignons dans la moitié de l’huile et en réserver la moitié.","Ajouter l’oignon et le reste de l’huile dans la poêle, puis faire revenir jusqu’à ce que l’oignon s’attendrisse. Ajouter l’orge et remuer une minute. Verser le bouillon chaud progressivement en remuant et cuire selon la durée indiquée sur le paquet, jusqu’à ce que l’orge soit tendre ; ajouter un peu d’eau chaude si nécessaire.","Incorporer les épinards et les laisser tomber, puis ajouter la ricotta et les champignons réservés. Servir quand l’ensemble est bien chaud."],
    conservation: "2 jours au réfrigérateur; réchauffer avec un peu d’eau.", image: "/assets/recipes/risotto-orge-champignons-epinards.jpg",
  },
  {
    id: "lasagnes-completes-legumes",
    title: "Lasagnes complètes aux légumes",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 50, costPerPortion: 2.9,
    seasons: ["summer", "autumn"], equipment: ["hob", "oven"], allergens: ["gluten", "lait"], tags: ["cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("wholewheat_lasagna", 75, "g"), ingredient("eggplant", 100, "g"), ingredient("zucchini", 100, "g"), ingredient("spinach", 60, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("ricotta", 65, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(520, 24, 12), description: "Des lasagnes végétariennes généreuses, à préparer aussi en avance.",
    steps: ["Préchauffer le four à 190 °C. Couper l’aubergine et la courgette en petits dés, puis les poêler dans l’huile avec l’ail haché jusqu’à tendreté. Ajouter les épinards et les laisser tomber.","Si le paquet l’exige, précuire les feuilles de lasagne selon ses instructions, puis les égoutter avant le montage. Dans un petit plat, alterner tomates, feuilles de lasagne, légumes et ricotta, en gardant suffisamment de tomate pour couvrir toutes les feuilles.","Cuire environ 25 minutes, ou selon les indications des feuilles utilisées, jusqu’à ce qu’elles soient tendres au centre ; couvrir si le dessus colore trop vite."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/lasagnes-completes-legumes.jpg",
  },
  {
    id: "moules-tomate-semoule-complete",
    title: "Moules à la tomate et semoule complète",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.75,
    seasons: ["summer", "autumn", "winter"], equipment: ["hob"], allergens: ["mollusques", "gluten"], tags: ["fruits-de-mer", "cereale-complete"],
    ingredients: [ingredient("mussel", 450, "g"), ingredient("wholewheat_couscous", 65, "g"), ingredient("crushed_tomato", 150, "g"), ingredient("fennel", 90, "g"), ingredient("onion", 45, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_cafe"), ingredient("parsley", 8, "g")],
    nutrition: nutrition(520, 39, 9), description: "Des moules parfumées à la tomate, servies avec une semoule complète.",
    steps: ["Trier et nettoyer les moules : jeter celles dont la coquille est cassée et celles qui restent ouvertes après une légère tape. Hacher l’oignon et l’ail, émincer finement le fenouil.","Faire revenir l’oignon, le fenouil et l’ail dans l’huile, puis ajouter les tomates et laisser mijoter jusqu’à ce que le fenouil s’attendrisse.","Ajouter les moules, couvrir et cuire à feu vif en secouant régulièrement la casserole jusqu’à ouverture. Jeter celles qui restent fermées.","Pendant ce temps, réhydrater la semoule avec la quantité d’eau bouillante et pendant la durée indiquées sur le paquet. Égrainer et servir avec les moules, la sauce et le persil haché."],
    conservation: "À consommer le jour même; ne pas conserver les moules non ouvertes.", image: "/assets/recipes/moules-tomate-semoule-complete.jpg",
  },
];

const BASE_PULSE_INGREDIENT_IDS = new Set([
  "chickpea",
  "green-lentil",
  "kidney-bean",
  "red-lentil",
  "tofu",
  "white-bean",
]);

function withWeeklyTargetTags(recipe: Recipe): Recipe {
  const targets = [
    ...(recipe.ingredients.some((item) => !item.optional && BASE_PULSE_INGREDIENT_IDS.has(item.id)) ? ["pulse"] : []),
    ...(recipe.allergens.includes("poisson") ? ["finfish"] : []),
    ...(recipe.allergens.some((allergen) => allergen === "mollusques" || allergen === "crustaces") ? ["seafood"] : []),
  ];
  return { ...recipe, tags: [...new Set([...targets, ...recipe.tags])] };
}

const BASE_RECIPES: readonly Recipe[] = BASE_RECIPE_SOURCE.map(withWeeklyTargetTags);

/** Existing V1 recipes plus the independently reviewed catalogue entries. */
export const RECIPES: readonly Recipe[] = [...BASE_RECIPES, ...IMPORTED_PLAN_RECIPES];

export { DEFAULT_PROFILE } from "./domain.ts";
