import type {
  Ingredient,
  IngredientCategory,
  IngredientUnit,
  Nutrition,
  Recipe,
} from "./domain";
import { IMPORTED_PLAN_RECIPES } from "./catalog";

type IngredientReference = {
  name: string;
  category: IngredientCategory;
  allergens?: readonly string[];
};

/** Single source of truth for ingredient labels, categories and allergens. */
const INGREDIENTS = {
  oats: { name: "flocons d’avoine", category: "grocery", allergens: ["gluten"] },
  blueberry: { name: "myrtilles", category: "fruit-vegetable" },
  strawberry: { name: "fraises", category: "fruit-vegetable" },
  raspberry: { name: "framboises", category: "fruit-vegetable" },
  walnut: { name: "noix", category: "grocery", allergens: ["fruits-a-coque"] },
  almond: { name: "amandes", category: "grocery", allergens: ["fruits-a-coque"] },
  almond_drink: { name: "boisson à l’amande", category: "beverage", allergens: ["fruits-a-coque"] },
  soy_drink: { name: "boisson au soja", category: "beverage", allergens: ["soja"] },
  yogurt: { name: "yaourt nature", category: "fresh", allergens: ["lait"] },
  kefir: { name: "kéfir nature", category: "fresh", allergens: ["lait"] },
  ricotta: { name: "ricotta", category: "fresh", allergens: ["lait"] },
  goat_cheese: { name: "fromage de chèvre", category: "fresh", allergens: ["lait"] },
  apple: { name: "pomme", category: "fruit-vegetable" },
  pear: { name: "poire", category: "fruit-vegetable" },
  banana: { name: "banane", category: "fruit-vegetable" },
  lemon: { name: "citron", category: "fruit-vegetable" },
  orange: { name: "orange", category: "fruit-vegetable" },
  avocado: { name: "avocat", category: "fruit-vegetable" },
  tomato: { name: "tomate", category: "fruit-vegetable" },
  cherry_tomato: { name: "tomates cerises", category: "fruit-vegetable" },
  cucumber: { name: "concombre", category: "fruit-vegetable" },
  carrot: { name: "carotte", category: "fruit-vegetable" },
  zucchini: { name: "courgette", category: "fruit-vegetable" },
  eggplant: { name: "aubergine", category: "fruit-vegetable" },
  bell_pepper: { name: "poivron", category: "fruit-vegetable" },
  broccoli: { name: "brocoli", category: "fruit-vegetable" },
  spinach: { name: "épinards", category: "fruit-vegetable" },
  mushroom: { name: "champignons", category: "fruit-vegetable" },
  green_bean: { name: "haricots verts", category: "fruit-vegetable" },
  fennel: { name: "fenouil", category: "fruit-vegetable" },
  beet: { name: "betterave cuite", category: "fruit-vegetable" },
  sweet_potato: { name: "patate douce", category: "fruit-vegetable" },
  potato: { name: "pomme de terre", category: "fruit-vegetable" },
  squash: { name: "courge", category: "fruit-vegetable" },
  leek: { name: "poireau", category: "fruit-vegetable" },
  onion: { name: "oignon", category: "fruit-vegetable" },
  garlic: { name: "ail", category: "fruit-vegetable" },
  parsley: { name: "persil", category: "fruit-vegetable" },
  basil: { name: "basilic", category: "fruit-vegetable" },
  mint: { name: "menthe", category: "fruit-vegetable" },
  dill: { name: "aneth", category: "fruit-vegetable" },
  egg: { name: "œuf", category: "fresh", allergens: ["oeuf"] },
  tofu: { name: "tofu ferme", category: "fresh", allergens: ["soja"] },
  chicken: { name: "blanc de poulet", category: "meat-fish" },
  turkey: { name: "dinde", category: "meat-fish" },
  salmon: { name: "saumon", category: "meat-fish", allergens: ["poisson"] },
  trout: { name: "truite", category: "meat-fish", allergens: ["poisson"] },
  sardine: { name: "sardines", category: "meat-fish", allergens: ["poisson"] },
  mackerel: { name: "maquereau", category: "meat-fish", allergens: ["poisson"] },
  tuna: { name: "thon au naturel", category: "meat-fish", allergens: ["poisson"] },
  cod: { name: "cabillaud", category: "meat-fish", allergens: ["poisson"] },
  sea_bass: { name: "bar", category: "meat-fish", allergens: ["poisson"] },
  mussel: { name: "moules", category: "meat-fish", allergens: ["mollusques"] },
  green_lentil: { name: "lentilles vertes cuites", category: "grocery" },
  red_lentil: { name: "lentilles corail", category: "grocery" },
  chickpea: { name: "pois chiches cuits", category: "grocery" },
  white_bean: { name: "haricots blancs cuits", category: "grocery" },
  kidney_bean: { name: "haricots rouges cuits", category: "grocery" },
  quinoa: { name: "quinoa cru", category: "grocery" },
  brown_rice: { name: "riz complet cru", category: "grocery" },
  barley: { name: "orge perlé cru", category: "grocery", allergens: ["gluten"] },
  farro: { name: "épeautre cru", category: "grocery", allergens: ["gluten"] },
  millet: { name: "millet cru", category: "grocery" },
  buckwheat_flour: { name: "farine de sarrasin", category: "grocery" },
  wholewheat_pasta: { name: "pâtes complètes crues", category: "grocery", allergens: ["gluten"] },
  wholewheat_couscous: { name: "semoule complète crue", category: "grocery", allergens: ["gluten"] },
  wholegrain_bread: { name: "pain complet", category: "bakery", allergens: ["gluten"] },
  wholegrain_wrap: { name: "galette complète", category: "bakery", allergens: ["gluten"] },
  wholewheat_lasagna: { name: "feuilles de lasagnes complètes", category: "grocery", allergens: ["gluten"] },
  chia: { name: "graines de chia", category: "grocery" },
  sesame: { name: "graines de sésame", category: "grocery", allergens: ["sesame"] },
  pumpkin_seed: { name: "graines de courge", category: "grocery" },
  hummus: { name: "houmous", category: "fresh", allergens: ["sesame"] },
  olive: { name: "olives", category: "grocery" },
  olive_oil: { name: "huile d’olive", category: "grocery" },
  coconut_milk: { name: "lait de coco", category: "grocery" },
  crushed_tomato: { name: "tomates concassées", category: "grocery" },
  cocoa: { name: "cacao non sucré", category: "grocery" },
  cinnamon: { name: "cannelle", category: "grocery" },
  turmeric: { name: "curcuma", category: "grocery" },
  cumin: { name: "cumin", category: "grocery" },
  paprika: { name: "paprika", category: "grocery" },
  ginger: { name: "gingembre", category: "fruit-vegetable" },
  mustard: { name: "moutarde", category: "grocery", allergens: ["moutarde"] },
  balsamic: { name: "vinaigre balsamique", category: "grocery" },
  vegetable_stock: { name: "bouillon de légumes", category: "grocery" },
} as const satisfies Record<string, IngredientReference>;

type IngredientId = keyof typeof INGREDIENTS;

function ingredient(id: IngredientId, quantity: number, unit: IngredientUnit): Ingredient {
  const reference: IngredientReference = INGREDIENTS[id];
  return {
    id,
    name: reference.name,
    quantity,
    unit,
    category: reference.category,
    ...(reference.allergens ? { allergens: reference.allergens } : {}),
  };
}

const NUTRITION_NOTE = "Valeurs nutritionnelles estimatives par portion, à titre indicatif." as const;

function nutrition(calories: number, protein: number, fiber: number): Nutrition {
  return { calories, protein, fiber, estimated: true, note: NUTRITION_NOTE };
}

const ALL_YEAR = ["all-year"] as const;
const VEGETARIAN = ["classic", "vegetarian", "no-pork"] as const;
const NO_PORK = ["classic", "no-pork"] as const;

const BASE_RECIPES: readonly Recipe[] = [
  {
    id: "overnight-oats-myrtilles-noix",
    title: "Overnight oats aux myrtilles et noix",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 8, costPerPortion: 1.7,
    seasons: ALL_YEAR, equipment: [], allergens: ["gluten", "fruits-a-coque"],
    tags: ["cereale-complete", "fruit", "sans-cuisson"],
    ingredients: [ingredient("oats", 50, "g"), ingredient("almond_drink", 140, "ml"), ingredient("blueberry", 80, "g"), ingredient("chia", 10, "g"), ingredient("walnut", 15, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(405, 11, 10), description: "Un petit-déjeuner préparé la veille, fruité et rassasiant.",
    steps: ["Mélanger les flocons, le chia, la cannelle et la boisson végétale.", "Réserver une nuit au frais.", "Ajouter les myrtilles et les noix au moment de servir."],
    conservation: "24 heures au réfrigérateur dans un récipient fermé.", image: "/assets/recipes/overnight-oats-myrtilles-noix.png",
  },
  {
    id: "yaourt-pomme-amandes",
    title: "Yaourt, pomme et amandes à la cannelle",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 6, costPerPortion: 1.45,
    seasons: ["autumn", "winter", "all-year"], equipment: [], allergens: ["lait", "fruits-a-coque"], tags: ["rapide", "fruit"],
    ingredients: [ingredient("yogurt", 150, "g"), ingredient("apple", 1, "piece"), ingredient("almond", 20, "g"), ingredient("oats", 30, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(350, 14, 7), description: "Un bol croquant qui associe fruit frais, céréales et produit laitier.",
    steps: ["Couper la pomme en petits dés.", "Verser le yaourt dans un bol et ajouter les flocons.", "Terminer avec la pomme, les amandes et la cannelle."],
    conservation: "À assembler juste avant dégustation.", image: "/assets/recipes/yaourt-pomme-amandes.png",
  },
  {
    id: "tartine-avocat-tomate-oeuf",
    title: "Tartine avocat, tomate et œuf",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 12, costPerPortion: 2.25,
    seasons: ["spring", "summer"], equipment: ["hob", "toaster"], allergens: ["gluten", "oeuf"], tags: ["cereale-complete", "vegetarien"],
    ingredients: [ingredient("wholegrain_bread", 70, "g"), ingredient("avocado", 0.5, "piece"), ingredient("tomato", 0.5, "piece"), ingredient("egg", 1, "piece"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 0.5, "c_cafe")],
    nutrition: nutrition(390, 15, 9), description: "Une tartine complète, fraîche et généreuse.",
    steps: ["Cuire l’œuf 7 minutes puis l’écaler.", "Écraser l’avocat avec le citron et toaster le pain.", "Garnir de tomate et d’œuf coupé en quartiers."],
    conservation: "À consommer immédiatement après assemblage.", image: "/assets/recipes/tartine-avocat-tomate-oeuf.png",
  },
  {
    id: "pudding-chia-poire-cacao",
    title: "Pudding de chia, poire et cacao",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 7, costPerPortion: 1.55,
    seasons: ["autumn", "winter"], equipment: [], allergens: ["soja"], tags: ["sans-gluten", "sans-cuisson", "fruit"],
    ingredients: [ingredient("chia", 30, "g"), ingredient("soy_drink", 180, "ml"), ingredient("pear", 1, "piece"), ingredient("cocoa", 1, "c_cafe"), ingredient("pumpkin_seed", 10, "g")],
    nutrition: nutrition(330, 12, 13), description: "Une crème de chia cacaotée adoucie par la poire.",
    steps: ["Mélanger le chia, le cacao et la boisson au soja.", "Laisser épaissir au moins 3 heures au frais.", "Ajouter la poire en dés et les graines de courge."],
    conservation: "Jusqu’à 2 jours au réfrigérateur.", image: "/assets/recipes/pudding-chia-poire-cacao.png",
  },
  {
    id: "porridge-millet-pomme",
    title: "Porridge de millet à la pomme",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 22, costPerPortion: 1.35,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["fruits-a-coque"], tags: ["sans-gluten", "chaud", "fruit"],
    ingredients: [ingredient("millet", 55, "g"), ingredient("almond_drink", 220, "ml"), ingredient("apple", 1, "piece"), ingredient("walnut", 15, "g"), ingredient("cinnamon", 0.5, "c_cafe")],
    nutrition: nutrition(415, 10, 8), description: "Un porridge chaud au millet pour changer de l’avoine.",
    steps: ["Rincer le millet et le cuire doucement dans la boisson végétale.", "Ajouter la moitié de la pomme râpée en fin de cuisson.", "Servir avec le reste de pomme, les noix et la cannelle."],
    conservation: "2 jours au frais; réchauffer avec un peu de boisson végétale.", image: "/assets/recipes/porridge-millet-pomme.png",
  },
  {
    id: "smoothie-kefir-fruits-rouges",
    title: "Smoothie kéfir et fruits rouges",
    mealTypes: ["breakfast"], diet: VEGETARIAN, prepMinutes: 5, costPerPortion: 1.85,
    seasons: ["spring", "summer"], equipment: ["blender"], allergens: ["lait", "gluten"], tags: ["rapide", "fruit"],
    ingredients: [ingredient("kefir", 180, "ml"), ingredient("strawberry", 80, "g"), ingredient("raspberry", 50, "g"), ingredient("banana", 0.5, "piece"), ingredient("oats", 25, "g"), ingredient("ginger", 5, "g")],
    nutrition: nutrition(285, 11, 7), description: "Un smoothie acidulé et consistant, prêt en quelques minutes.",
    steps: ["Équeuter les fraises.", "Mixer tous les ingrédients jusqu’à texture lisse.", "Servir sans attendre."],
    conservation: "À boire le jour même, idéalement juste après mixage.", image: "/assets/recipes/smoothie-kefir-fruits-rouges.png",
  },
  {
    id: "galette-sarrasin-epinards-ricotta",
    title: "Galette de sarrasin, épinards et ricotta",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.1,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["oeuf", "lait"], tags: ["sans-gluten", "vegetarien"],
    ingredients: [ingredient("buckwheat_flour", 55, "g"), ingredient("egg", 1, "piece"), ingredient("spinach", 80, "g"), ingredient("ricotta", 45, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(365, 18, 6), description: "Une galette salée souple, garnie de verdure et de ricotta.",
    steps: ["Délayer la farine avec 100 ml d’eau et la moitié de l’œuf battu.", "Cuire la galette puis faire tomber les épinards à l’huile.", "Garnir de ricotta, épinards et du reste d’œuf cuit."],
    conservation: "La galette et la garniture se gardent séparément 24 heures au frais.", image: "/assets/recipes/galette-sarrasin-epinards-ricotta.png",
  },
  {
    id: "tofu-brouille-champignons",
    title: "Tofu brouillé aux champignons",
    mealTypes: ["breakfast", "lunch"], diet: VEGETARIAN, prepMinutes: 15, costPerPortion: 2.05,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["soja", "gluten"], tags: ["vegetarien", "rapide"],
    ingredients: [ingredient("tofu", 140, "g"), ingredient("mushroom", 100, "g"), ingredient("spinach", 50, "g"), ingredient("wholegrain_bread", 50, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("turmeric", 0.5, "c_cafe")],
    nutrition: nutrition(360, 25, 7), description: "Une assiette salée végétarienne, fondante et rapide.",
    steps: ["Émincer et dorer les champignons.", "Émietter le tofu, ajouter le curcuma et cuire 5 minutes.", "Incorporer les épinards et servir avec le pain toasté."],
    conservation: "2 jours au réfrigérateur sans le pain.", image: "/assets/recipes/tofu-brouille-champignons.png",
  },
  {
    id: "salade-lentilles-noix",
    title: "Salade de lentilles, légumes et noix",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 18, costPerPortion: 2.35,
    seasons: ALL_YEAR, equipment: [], allergens: ["fruits-a-coque", "moutarde"], tags: ["legumineuse", "sans-gluten", "meal-prep"],
    ingredients: [ingredient("green_lentil", 180, "g"), ingredient("carrot", 70, "g"), ingredient("cucumber", 80, "g"), ingredient("walnut", 20, "g"), ingredient("parsley", 10, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(460, 19, 16), description: "Une salade de lentilles croquante, facile à emporter.",
    steps: ["Couper finement les légumes et hacher le persil.", "Mélanger la moutarde et l’huile pour la vinaigrette.", "Réunir lentilles, légumes et noix, puis assaisonner."],
    conservation: "3 jours au réfrigérateur; ajouter les noix au dernier moment.", image: "/assets/recipes/salade-lentilles-noix.png",
  },
  {
    id: "bowl-quinoa-legumes-houmous",
    title: "Bowl quinoa, légumes rôtis et houmous",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 3.05,
    seasons: ["summer", "autumn"], equipment: ["hob", "oven"], allergens: ["sesame"], tags: ["cereale-complete", "vegetarien", "meal-prep"],
    ingredients: [ingredient("quinoa", 70, "g"), ingredient("zucchini", 120, "g"), ingredient("bell_pepper", 100, "g"), ingredient("chickpea", 80, "g"), ingredient("hummus", 45, "g"), ingredient("olive_oil", 1, "c_soupe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(555, 19, 13), description: "Un bol coloré avec quinoa, légumes dorés et houmous crémeux.",
    steps: ["Rôtir courgette et poivron huilés 20 minutes à 210 °C.", "Cuire le quinoa puis l’égrainer.", "Assembler avec les pois chiches, le houmous et le citron."],
    conservation: "3 jours au frais, houmous conservé séparément.", image: "/assets/recipes/bowl-quinoa-legumes-houmous.png",
  },
  {
    id: "salade-haricots-blancs-tomates",
    title: "Salade de haricots blancs aux tomates",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 12, costPerPortion: 2.15,
    seasons: ["spring", "summer"], equipment: [], allergens: [], tags: ["legumineuse", "sans-gluten", "rapide"],
    ingredients: [ingredient("white_bean", 190, "g"), ingredient("cherry_tomato", 120, "g"), ingredient("cucumber", 90, "g"), ingredient("olive", 25, "g"), ingredient("basil", 8, "g"), ingredient("olive_oil", 1, "c_soupe"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(410, 17, 14), description: "Une salade méditerranéenne économique et sans cuisson.",
    steps: ["Rincer et égoutter les haricots.", "Couper les tomates, le concombre et les olives.", "Mélanger avec le basilic, le citron et l’huile."],
    conservation: "2 jours au réfrigérateur dans une boîte hermétique.", image: "/assets/recipes/salade-haricots-blancs-tomates.png",
  },
  {
    id: "taboule-pois-chiches-complet",
    title: "Taboulé complet aux pois chiches",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.25,
    seasons: ["spring", "summer"], equipment: ["hob"], allergens: ["gluten"], tags: ["legumineuse", "cereale-complete", "meal-prep"],
    ingredients: [ingredient("wholewheat_couscous", 65, "g"), ingredient("chickpea", 120, "g"), ingredient("tomato", 1, "piece"), ingredient("cucumber", 80, "g"), ingredient("parsley", 12, "g"), ingredient("mint", 6, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(505, 18, 13), description: "Un taboulé généreux en herbes, céréales complètes et pois chiches.",
    steps: ["Réhydrater la semoule puis l’égrainer.", "Détailler les légumes et ciseler les herbes.", "Mélanger avec les pois chiches, le citron et l’huile."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/taboule-pois-chiches-complet.png",
  },
  {
    id: "pates-completes-ratatouille",
    title: "Pâtes complètes à la ratatouille",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.3,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: ["gluten"], tags: ["cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("wholewheat_pasta", 80, "g"), ingredient("eggplant", 90, "g"), ingredient("zucchini", 90, "g"), ingredient("bell_pepper", 70, "g"), ingredient("crushed_tomato", 130, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("basil", 6, "g")],
    nutrition: nutrition(480, 17, 12), description: "Des pâtes complètes enrobées d’une ratatouille fondante.",
    steps: ["Faire revenir les légumes en dés avec l’ail et l’huile.", "Ajouter la tomate et mijoter pendant la cuisson des pâtes.", "Mélanger les pâtes égouttées à la sauce et ajouter le basilic."],
    conservation: "3 jours au réfrigérateur; réchauffer doucement.", image: "/assets/recipes/pates-completes-ratatouille.png",
  },
  {
    id: "salade-sardines-pommes-terre-haricots",
    title: "Salade de sardines, pommes de terre et haricots verts",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.15,
    seasons: ["spring", "summer"], equipment: ["hob"], allergens: ["poisson", "moutarde"], tags: ["poisson-gras", "sans-gluten"],
    ingredients: [ingredient("sardine", 100, "g"), ingredient("potato", 180, "g"), ingredient("green_bean", 120, "g"), ingredient("cherry_tomato", 80, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(515, 31, 9), description: "Une salade tiède complète au poisson gras.",
    steps: ["Cuire les pommes de terre et les haricots verts à l’eau.", "Préparer une vinaigrette avec moutarde, citron et huile.", "Assembler les légumes tièdes, les tomates et les sardines."],
    conservation: "24 heures au réfrigérateur; conserver la vinaigrette à part.", image: "/assets/recipes/salade-sardines-pommes-terre-haricots.png",
  },
  {
    id: "salade-thon-haricots-rouges",
    title: "Salade de thon et haricots rouges",
    mealTypes: ["lunch"], diet: NO_PORK, prepMinutes: 12, costPerPortion: 2.8,
    seasons: ALL_YEAR, equipment: [], allergens: ["poisson"], tags: ["poisson-maigre", "legumineuse", "rapide"],
    ingredients: [ingredient("tuna", 100, "g"), ingredient("kidney_bean", 150, "g"), ingredient("tomato", 1, "piece"), ingredient("bell_pepper", 70, "g"), ingredient("onion", 30, "g"), ingredient("parsley", 8, "g"), ingredient("lemon", 0.25, "piece"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(440, 38, 12), description: "Une salade express riche en textures et facile à emporter.",
    steps: ["Rincer les haricots et égoutter le thon.", "Émincer les légumes et le persil.", "Tout mélanger avec le citron et l’huile."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/salade-thon-haricots-rouges.png",
  },
  {
    id: "bowl-saumon-riz-complet-avocat",
    title: "Bowl saumon, riz complet et avocat",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 4.75,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["poisson", "sesame"], tags: ["poisson-gras", "cereale-complete"],
    ingredients: [ingredient("salmon", 120, "g"), ingredient("brown_rice", 70, "g"), ingredient("avocado", 0.5, "piece"), ingredient("cucumber", 80, "g"), ingredient("carrot", 60, "g"), ingredient("sesame", 8, "g"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(650, 36, 10), description: "Un bowl complet au saumon poêlé et aux légumes croquants.",
    steps: ["Cuire le riz complet et le laisser tiédir.", "Poêler le saumon puis détailler les légumes.", "Assembler le bowl, arroser de citron et parsemer de sésame."],
    conservation: "24 heures au réfrigérateur sans l’avocat, à ajouter au service.", image: "/assets/recipes/bowl-saumon-riz-complet-avocat.png",
  },
  {
    id: "bowl-poulet-orge-legumes",
    title: "Bowl de poulet, orge et légumes",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 3.35,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["gluten", "moutarde"], tags: ["volaille", "cereale-complete", "meal-prep"],
    ingredients: [ingredient("chicken", 130, "g"), ingredient("barley", 65, "g"), ingredient("broccoli", 110, "g"), ingredient("carrot", 70, "g"), ingredient("spinach", 50, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(545, 45, 11), description: "Un bowl de volaille, orge moelleuse et légumes verts.",
    steps: ["Cuire l’orge dans l’eau frémissante.", "Poêler le poulet et cuire les légumes jusqu’à ce qu’ils restent légèrement croquants.", "Assembler avec une vinaigrette moutardée."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/bowl-poulet-orge-legumes.png",
  },
  {
    id: "wrap-dinde-crudites-houmous",
    title: "Wrap complet de dinde, crudités et houmous",
    mealTypes: ["lunch"], diet: NO_PORK, prepMinutes: 15, costPerPortion: 3.05,
    seasons: ALL_YEAR, equipment: [], allergens: ["gluten", "sesame"], tags: ["volaille", "rapide", "a-emporter"],
    ingredients: [ingredient("wholegrain_wrap", 1, "piece"), ingredient("turkey", 100, "g"), ingredient("hummus", 40, "g"), ingredient("carrot", 60, "g"), ingredient("cucumber", 70, "g"), ingredient("spinach", 35, "g"), ingredient("lemon", 0.25, "piece")],
    nutrition: nutrition(475, 35, 9), description: "Un wrap frais, pratique et généreusement garni.",
    steps: ["Étaler le houmous sur la galette.", "Ajouter la dinde, les crudités taillées finement et les épinards.", "Arroser de citron, rouler serré et couper en deux."],
    conservation: "24 heures au frais, bien emballé.", image: "/assets/recipes/wrap-dinde-crudites-houmous.png",
  },
  {
    id: "bowl-cabillaud-patate-douce",
    title: "Bowl de cabillaud et patate douce",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 4.1,
    seasons: ALL_YEAR, equipment: ["oven"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten"],
    ingredients: [ingredient("cod", 140, "g"), ingredient("sweet_potato", 180, "g"), ingredient("broccoli", 110, "g"), ingredient("spinach", 45, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("paprika", 0.5, "c_cafe")],
    nutrition: nutrition(470, 38, 11), description: "Un bowl au cabillaud rôti, doux et coloré.",
    steps: ["Rôtir les cubes de patate douce huilés 20 minutes à 210 °C.", "Ajouter le brocoli et le cabillaud assaisonné pour 10 minutes.", "Servir sur les épinards avec le citron."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/bowl-cabillaud-patate-douce.png",
  },
  {
    id: "mijote-aubergine-pois-chiches",
    title: "Mijoté d’aubergine et pois chiches",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 2.2,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("eggplant", 180, "g"), ingredient("chickpea", 160, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("cumin", 0.5, "c_cafe"), ingredient("parsley", 8, "g")],
    nutrition: nutrition(430, 16, 15), description: "Un plat mijoté végétarien aux saveurs méditerranéennes.",
    steps: ["Faire revenir l’oignon, l’ail et l’aubergine dans l’huile.", "Ajouter tomates, pois chiches et cumin puis mijoter 18 minutes.", "Parsemer de persil avant de servir."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/mijote-aubergine-pois-chiches.png",
  },
  {
    id: "salade-betterave-chevre-lentilles",
    title: "Salade de betterave, chèvre et lentilles",
    mealTypes: ["lunch"], diet: VEGETARIAN, prepMinutes: 14, costPerPortion: 2.65,
    seasons: ["autumn", "winter", "spring"], equipment: [], allergens: ["lait", "fruits-a-coque"], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("green_lentil", 160, "g"), ingredient("beet", 140, "g"), ingredient("goat_cheese", 45, "g"), ingredient("walnut", 15, "g"), ingredient("spinach", 45, "g"), ingredient("balsamic", 1, "c_soupe"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(455, 22, 13), description: "Une salade terreuse et acidulée, adoucie par le chèvre.",
    steps: ["Couper la betterave et le fromage de chèvre.", "Mélanger vinaigre et huile.", "Assembler avec les lentilles, les épinards et les noix."],
    conservation: "2 jours au réfrigérateur, assaisonnement séparé.", image: "/assets/recipes/salade-betterave-chevre-lentilles.png",
  },
  {
    id: "salade-maquereau-betterave-pomme-terre",
    title: "Salade de maquereau, betterave et pomme de terre",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.3,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["poisson", "moutarde"], tags: ["poisson-gras", "sans-gluten"],
    ingredients: [ingredient("mackerel", 110, "g"), ingredient("beet", 120, "g"), ingredient("potato", 170, "g"), ingredient("spinach", 45, "g"), ingredient("mustard", 1, "c_cafe"), ingredient("lemon", 0.25, "piece"), ingredient("dill", 5, "g")],
    nutrition: nutrition(530, 32, 8), description: "Une salade hivernale au maquereau et aux légumes racines.",
    steps: ["Cuire les pommes de terre puis les couper en quartiers.", "Mélanger moutarde, citron et aneth.", "Assembler avec la betterave, les épinards et le maquereau."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/salade-maquereau-betterave-pomme-terre.png",
  },
  {
    id: "saumon-brocoli-riz-complet",
    title: "Saumon, brocoli et riz complet",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 28, costPerPortion: 4.55,
    seasons: ALL_YEAR, equipment: ["hob", "steamer"], allergens: ["poisson"], tags: ["poisson-gras", "cereale-complete"],
    ingredients: [ingredient("salmon", 140, "g"), ingredient("broccoli", 180, "g"), ingredient("brown_rice", 70, "g"), ingredient("lemon", 0.5, "piece"), ingredient("olive_oil", 1, "c_cafe"), ingredient("dill", 5, "g")],
    nutrition: nutrition(610, 42, 10), description: "Une assiette simple de saumon, brocoli vapeur et riz complet.",
    steps: ["Cuire le riz complet selon les indications du paquet.", "Cuire le brocoli à la vapeur et poêler le saumon.", "Servir avec citron, aneth et un filet d’huile."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/saumon-brocoli-riz-complet.png",
  },
  {
    id: "curry-pois-chiches-epinards",
    title: "Curry de pois chiches et épinards",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 24, costPerPortion: 2.4,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten"],
    ingredients: [ingredient("chickpea", 180, "g"), ingredient("spinach", 120, "g"), ingredient("crushed_tomato", 120, "g"), ingredient("coconut_milk", 100, "ml"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("ginger", 5, "g")],
    nutrition: nutrition(480, 17, 14), description: "Un curry végétarien crémeux aux épices douces.",
    steps: ["Faire revenir l’oignon, l’ail, le gingembre et le curcuma.", "Ajouter tomates, lait de coco et pois chiches puis mijoter 12 minutes.", "Faire tomber les épinards dans la sauce en fin de cuisson."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/curry-pois-chiches-epinards.png",
  },
  {
    id: "omelette-legumes-quinoa",
    title: "Omelette aux légumes et quinoa",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 20, costPerPortion: 2.45,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["oeuf"], tags: ["vegetarien", "sans-gluten", "anti-gaspi"],
    ingredients: [ingredient("egg", 2, "piece"), ingredient("quinoa", 45, "g"), ingredient("zucchini", 80, "g"), ingredient("mushroom", 70, "g"), ingredient("spinach", 45, "g"), ingredient("olive_oil", 1, "c_cafe"), ingredient("parsley", 6, "g")],
    nutrition: nutrition(430, 25, 7), description: "Une omelette complète qui accueille facilement les légumes restants.",
    steps: ["Cuire le quinoa et poêler les légumes.", "Battre les œufs avec le persil puis verser sur les légumes.", "Cuire à feu doux et servir avec le quinoa."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/omelette-legumes-quinoa.png",
  },
  {
    id: "truite-haricots-verts-quinoa",
    title: "Truite, haricots verts et quinoa",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 4.25,
    seasons: ALL_YEAR, equipment: ["hob", "steamer"], allergens: ["poisson"], tags: ["poisson-gras", "sans-gluten", "cereale-complete"],
    ingredients: [ingredient("trout", 140, "g"), ingredient("green_bean", 160, "g"), ingredient("quinoa", 65, "g"), ingredient("lemon", 0.5, "piece"), ingredient("dill", 5, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(555, 41, 9), description: "Une assiette légère en apparence, mais complète et rassasiante.",
    steps: ["Cuire le quinoa et les haricots verts.", "Poêler la truite côté peau puis retourner brièvement.", "Servir avec citron, aneth et huile d’olive."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/truite-haricots-verts-quinoa.png",
  },
  {
    id: "bowl-tofu-brocoli-sesame",
    title: "Bowl tofu, brocoli et sésame",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 22, costPerPortion: 2.85,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["soja", "sesame"], tags: ["vegetarien", "sans-gluten", "cereale-complete"],
    ingredients: [ingredient("tofu", 150, "g"), ingredient("broccoli", 160, "g"), ingredient("brown_rice", 65, "g"), ingredient("carrot", 60, "g"), ingredient("sesame", 10, "g"), ingredient("ginger", 5, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(540, 29, 11), description: "Un bowl végétarien au tofu doré et au brocoli croquant.",
    steps: ["Cuire le riz et détailler les légumes.", "Dorer le tofu avec le gingembre puis ajouter brocoli et carotte.", "Servir sur le riz et parsemer de sésame."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/bowl-tofu-brocoli-sesame.png",
  },
  {
    id: "cabillaud-tomate-olives",
    title: "Cabillaud mijoté à la tomate et aux olives",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 4.05,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten", "mediterraneen"],
    ingredients: [ingredient("cod", 150, "g"), ingredient("crushed_tomato", 200, "g"), ingredient("olive", 30, "g"), ingredient("zucchini", 120, "g"), ingredient("onion", 50, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("parsley", 6, "g")],
    nutrition: nutrition(360, 38, 7), description: "Un cabillaud tendre dans une sauce tomate aux olives.",
    steps: ["Faire revenir oignon, ail et courgette dans l’huile.", "Ajouter tomate et olives puis mijoter 10 minutes.", "Déposer le cabillaud dans la sauce, couvrir et cuire 8 minutes."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/cabillaud-tomate-olives.png",
  },
  {
    id: "poulet-curcuma-legumes-semoule",
    title: "Poulet au curcuma, légumes et semoule complète",
    mealTypes: ["lunch", "dinner"], diet: NO_PORK, prepMinutes: 28, costPerPortion: 3.35,
    seasons: ALL_YEAR, equipment: ["hob"], allergens: ["gluten"], tags: ["volaille", "cereale-complete", "batch-cooking"],
    ingredients: [ingredient("chicken", 140, "g"), ingredient("wholewheat_couscous", 65, "g"), ingredient("carrot", 80, "g"), ingredient("zucchini", 100, "g"), ingredient("chickpea", 60, "g"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("cumin", 0.5, "c_cafe"), ingredient("olive_oil", 1, "c_soupe")],
    nutrition: nutrition(590, 47, 11), description: "Une assiette de poulet épicé doucement, semoule et légumes.",
    steps: ["Dorer le poulet avec le curcuma et le cumin.", "Ajouter carotte et courgette puis cuire à couvert.", "Réhydrater la semoule, ajouter les pois chiches et servir ensemble."],
    conservation: "3 jours au réfrigérateur.", image: "/assets/recipes/poulet-curcuma-legumes-semoule.png",
  },
  {
    id: "boulettes-dinde-courgette-tomate",
    title: "Boulettes de dinde, courgette et tomate",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 3.45,
    seasons: ["summer", "autumn"], equipment: ["hob"], allergens: ["oeuf"], tags: ["volaille", "sans-gluten"],
    ingredients: [ingredient("turkey", 150, "g"), ingredient("egg", 0.25, "piece"), ingredient("zucchini", 130, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("onion", 40, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("basil", 6, "g")],
    nutrition: nutrition(390, 40, 6), description: "Des boulettes de dinde moelleuses dans une sauce tomate aux courgettes.",
    steps: ["Mélanger la dinde, l’œuf et la moitié de l’oignon puis former des boulettes.", "Dorer les boulettes et réserver.", "Mijoter courgette, ail et tomate puis remettre les boulettes 10 minutes."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/boulettes-dinde-courgette-tomate.png",
  },
  {
    id: "bar-four-fenouil-pommes-terre",
    title: "Bar au four, fenouil et pommes de terre",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 30, costPerPortion: 4.8,
    seasons: ["autumn", "winter", "spring"], equipment: ["oven"], allergens: ["poisson"], tags: ["poisson-maigre", "sans-gluten"],
    ingredients: [ingredient("sea_bass", 150, "g"), ingredient("fennel", 140, "g"), ingredient("potato", 180, "g"), ingredient("lemon", 0.5, "piece"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_soupe"), ingredient("dill", 5, "g")],
    nutrition: nutrition(475, 37, 8), description: "Un poisson blanc rôti avec fenouil fondant et pommes de terre.",
    steps: ["Précuire les pommes de terre en fines rondelles 10 minutes.", "Disposer avec le fenouil, l’ail et l’huile puis rôtir 10 minutes.", "Ajouter le bar et le citron, puis cuire encore 10 minutes."],
    conservation: "24 heures au réfrigérateur.", image: "/assets/recipes/bar-four-fenouil-pommes-terre.png",
  },
  {
    id: "dal-lentilles-corail-courge",
    title: "Dal de lentilles corail et courge",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 28, costPerPortion: 1.95,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: [], tags: ["legumineuse", "vegetarien", "sans-gluten", "batch-cooking"],
    ingredients: [ingredient("red_lentil", 85, "g"), ingredient("squash", 180, "g"), ingredient("coconut_milk", 90, "ml"), ingredient("crushed_tomato", 100, "g"), ingredient("onion", 50, "g"), ingredient("ginger", 5, "g"), ingredient("turmeric", 0.5, "c_cafe"), ingredient("cumin", 0.5, "c_cafe")],
    nutrition: nutrition(475, 19, 15), description: "Un dal doux et velouté aux lentilles corail et à la courge.",
    steps: ["Faire revenir l’oignon, le gingembre et les épices.", "Ajouter courge, lentilles, tomate et 180 ml d’eau puis mijoter.", "Verser le lait de coco et cuire jusqu’à texture crémeuse."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/dal-lentilles-corail-courge.png",
  },
  {
    id: "minestrone-haricots-blancs-epeautre",
    title: "Minestrone aux haricots blancs et épeautre",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.15,
    seasons: ["autumn", "winter", "spring"], equipment: ["hob"], allergens: ["gluten"], tags: ["legumineuse", "cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("white_bean", 140, "g"), ingredient("farro", 55, "g"), ingredient("carrot", 70, "g"), ingredient("leek", 70, "g"), ingredient("zucchini", 70, "g"), ingredient("crushed_tomato", 130, "g"), ingredient("vegetable_stock", 350, "ml"), ingredient("basil", 5, "g")],
    nutrition: nutrition(445, 19, 16), description: "Une soupe-repas italienne aux légumes, haricots et épeautre.",
    steps: ["Faire suer les légumes coupés en petits dés.", "Ajouter épeautre, tomate et bouillon puis cuire 22 minutes.", "Ajouter les haricots pour les 5 dernières minutes et servir avec le basilic."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/minestrone-haricots-blancs-epeautre.png",
  },
  {
    id: "risotto-orge-champignons-epinards",
    title: "Orge crémeuse aux champignons et épinards",
    mealTypes: ["dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.45,
    seasons: ["autumn", "winter"], equipment: ["hob"], allergens: ["gluten", "lait"], tags: ["cereale-complete", "vegetarien"],
    ingredients: [ingredient("barley", 80, "g"), ingredient("mushroom", 160, "g"), ingredient("spinach", 80, "g"), ingredient("onion", 45, "g"), ingredient("vegetable_stock", 320, "ml"), ingredient("ricotta", 35, "g"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(455, 18, 12), description: "Une orge façon risotto, crémeuse et riche en champignons.",
    steps: ["Dorer les champignons et réserver la moitié.", "Nacrer l’orge avec l’oignon puis ajouter le bouillon progressivement.", "Incorporer épinards, ricotta et champignons en fin de cuisson."],
    conservation: "2 jours au réfrigérateur; réchauffer avec un peu d’eau.", image: "/assets/recipes/risotto-orge-champignons-epinards.png",
  },
  {
    id: "lasagnes-completes-legumes",
    title: "Lasagnes complètes aux légumes",
    mealTypes: ["lunch", "dinner"], diet: VEGETARIAN, prepMinutes: 30, costPerPortion: 2.9,
    seasons: ["summer", "autumn"], equipment: ["hob", "oven"], allergens: ["gluten", "lait"], tags: ["cereale-complete", "vegetarien", "batch-cooking"],
    ingredients: [ingredient("wholewheat_lasagna", 75, "g"), ingredient("eggplant", 100, "g"), ingredient("zucchini", 100, "g"), ingredient("spinach", 60, "g"), ingredient("crushed_tomato", 180, "g"), ingredient("ricotta", 65, "g"), ingredient("garlic", 0.5, "piece"), ingredient("olive_oil", 1, "c_cafe")],
    nutrition: nutrition(520, 24, 12), description: "Des lasagnes végétariennes généreuses, à préparer aussi en avance.",
    steps: ["Poêler aubergine et courgette avec l’ail puis ajouter les épinards.", "Alterner tomate, feuilles de lasagne, légumes et ricotta dans un plat.", "Cuire 25 minutes à 190 °C; le temps actif reste inférieur à 30 minutes."],
    conservation: "3 jours au réfrigérateur ou 2 mois au congélateur.", image: "/assets/recipes/lasagnes-completes-legumes.png",
  },
  {
    id: "moules-tomate-semoule-complete",
    title: "Moules à la tomate et semoule complète",
    mealTypes: ["dinner"], diet: NO_PORK, prepMinutes: 25, costPerPortion: 3.75,
    seasons: ["summer", "autumn", "winter"], equipment: ["hob"], allergens: ["mollusques", "gluten"], tags: ["fruits-de-mer", "cereale-complete"],
    ingredients: [ingredient("mussel", 450, "g"), ingredient("wholewheat_couscous", 65, "g"), ingredient("crushed_tomato", 150, "g"), ingredient("fennel", 90, "g"), ingredient("onion", 45, "g"), ingredient("garlic", 1, "piece"), ingredient("olive_oil", 1, "c_cafe"), ingredient("parsley", 8, "g")],
    nutrition: nutrition(520, 39, 9), description: "Des moules parfumées à la tomate, servies avec une semoule complète.",
    steps: ["Faire revenir oignon, fenouil et ail puis ajouter la tomate.", "Ajouter les moules nettoyées, couvrir et cuire jusqu’à ouverture; jeter celles restées fermées.", "Réhydrater la semoule et servir avec le persil."],
    conservation: "À consommer le jour même; ne pas conserver les moules non ouvertes.", image: "/assets/recipes/moules-tomate-semoule-complete.png",
  },
];

/** Existing V1 recipes plus the independently reviewed catalogue entries. */
export const RECIPES: readonly Recipe[] = [...BASE_RECIPES, ...IMPORTED_PLAN_RECIPES];

export { DEFAULT_PROFILE } from "./domain";
